In [8]:
import sys
!conda install --yes --prefix {sys.prefix} openpyxl

zsh:1: command not found: conda

In [10]:
#Combine all pages into one sheet

import os
import pandas as pd
import openpyxl

cwd = os.path.abspath('')
files = os.listdir(cwd)
df_toAppend = pd.DataFrame()

for file in files:
    if file.endswith('.xlsx'):
        df_toAppend = pd.concat(pd.read_excel(file, sheet_name=None), ignore_index=True)
        df_toAppend.to_excel(file)

df_toAppend.head()

ModuleNotFoundError: No module named 'openpyxl'

In [2]:
import pandas as pd

all_df = pd.concat(pd.read_excel('PEH TTO Data.xlsx', sheet_name=None), ignore_index=True)

all_df.head()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,2021-01-04 00:00:00,4A,4811,3.021e+09,09:52:00,NaN,10:00:00,10:10:00,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-04 00:00:00,3A,3828,3.02004e+09,08:34:00,NaN,08:44:00,NaN,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-04 00:00:00,3B,3606,3.021e+09,09:15:00,09:40:00,09:50:00,09:55:00,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-04 00:00:00,DAY,2011,3.021e+09,10:09:00,NaN,10:20:00,NaN,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-01-04 00:00:00,4B,4610,3.02004e+09,08:37:00,NaN,08:47:00,NaN,PATIENT FOR HOME ON WED,YSM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN