# PEH Pharmacy Department

In [1]:
import pandas as pd
import numpy as np

# DO NOT RUN THIS SECTION

## Combining Excel Tabs and Basic Cleaning

In [122]:
#Combining all Excel sheets into one --Assuming all have the same headers

f = '../PEH TTO Data.xlsx'
df = pd.read_excel(f, sheet_name=None)
df2 = pd.concat(df, ignore_index=True)

df2.head()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,2021-01-04 00:00:00,4A,4811,3.021e+09,09:52:00,NaN,10:00:00,10:10:00,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-04 00:00:00,3A,3828,3.02004e+09,08:34:00,NaN,08:44:00,NaN,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-04 00:00:00,3B,3606,3.021e+09,09:15:00,09:40:00,09:50:00,09:55:00,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-04 00:00:00,DAY,2011,3.021e+09,10:09:00,NaN,10:20:00,NaN,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-01-04 00:00:00,4B,4610,3.02004e+09,08:37:00,NaN,08:47:00,NaN,PATIENT FOR HOME ON WED,YSM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
#drop unnecessary columns --unnamed
df2.drop(df2.columns[df2.columns.str.contains('Unnamed')], axis=1, inplace=True)
df2.head()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
0,2021-01-04 00:00:00,4A,4811,3.021e+09,09:52:00,NaN,10:00:00,10:10:00,NaN,TFP,00:08:00,00:18:00,3,Yes,TFP,NaN,NaN
1,2021-01-04 00:00:00,3A,3828,3.02004e+09,08:34:00,NaN,08:44:00,NaN,NaN,TFP,00:10:00,NaN,NaN,,NaN,NaN,NaN
2,2021-01-04 00:00:00,3B,3606,3.021e+09,09:15:00,09:40:00,09:50:00,09:55:00,NaN,TFP,00:10:00,00:15:00,2,Yes,TFP,NaN,NaN
3,2021-01-04 00:00:00,DAY,2011,3.021e+09,10:09:00,NaN,10:20:00,NaN,NaN,TFP,00:11:00,NaN,NaN,,NaN,NaN,NaN
4,2021-01-04 00:00:00,4B,4610,3.02004e+09,08:37:00,NaN,08:47:00,NaN,PATIENT FOR HOME ON WED,YSM,00:10:00,NaN,NaN,NaN,NaN,NaN,NaN

In [124]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3450 entries, 0 to 3449
Data columns (total 17 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Date                                                          3251 non-null   object
 1   Ward                                                          3237 non-null   object
 2   Room                                                          3243 non-null   object
 3   Case Number                                                   3244 non-null   object
 4   Verified                                                      3248 non-null   object
 5   Meds Sent Down                                                318 non-null    object
 6   Checked                                                       3249 non-null   object
 7   Counselled                                                    996 non-null    object
 8   Remarks
(input paeds if it is a 4P patient in 4A)             2425 non-null   object
 9   Checked by Pharmacist                                         3243 non-null   object
 10  Time to Ready for Collection                                  3244 non-null   object
 11  Time to Counselling                                           992 non-null    object
 12  No. of Items                                                  988 non-null    object
 13  Bedside Counselling Candidate                                 2759 non-null   object
 14  Dispensed by                                                  993 non-null    object
 15  PML given?                                                    563 non-null    object
 16  If not given, WHY?! If given, were any interventions needed?  268 non-null    object
dtypes: object(17)
memory usage: 458.3+ KB

In [125]:
df2.dropna(axis = 0, how = 'all', inplace = True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3281 entries, 0 to 3449
Data columns (total 17 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Date                                                          3251 non-null   object
 1   Ward                                                          3237 non-null   object
 2   Room                                                          3243 non-null   object
 3   Case Number                                                   3244 non-null   object
 4   Verified                                                      3248 non-null   object
 5   Meds Sent Down                                                318 non-null    object
 6   Checked                                                       3249 non-null   object
 7   Counselled                                                    996 non-null    object
 8   Remarks
(input paeds if it is a 4P patient in 4A)             2425 non-null   object
 9   Checked by Pharmacist                                         3243 non-null   object
 10  Time to Ready for Collection                                  3244 non-null   object
 11  Time to Counselling                                           992 non-null    object
 12  No. of Items                                                  988 non-null    object
 13  Bedside Counselling Candidate                                 2759 non-null   object
 14  Dispensed by                                                  993 non-null    object
 15  PML given?                                                    563 non-null    object
 16  If not given, WHY?! If given, were any interventions needed?  268 non-null    object
dtypes: object(17)
memory usage: 461.4+ KB

In [126]:
df2.tail()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
3442,2021-12-31 00:00:00,3B,3610,3.02105e+09,15:10:00,NaN,15:25:00,NaN,NaN,DH,00:15:00,NaN,NaN,,NaN,NaN,NaN
3443,2021-12-31 00:00:00,3B,3605,3.02105e+09,16:26:00,NaN,16:32:00,NaN,NaN,DH,00:06:00,NaN,NaN,,NaN,NaN,NaN
3447,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3448,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3449,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN

In [127]:
df2.drop(df2.tail(3).index,inplace=True)

In [128]:
df2.tail()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
3439,2021-12-31 00:00:00,3B,3611,3.02105e+09,09:50:00,NaN,10:08:00,10:26:00,NaN,TCE,00:18:00,00:36:00,6,Yes,TCE,NaN,NaN
3440,2021-12-31 00:00:00,3B,3620,3.02105e+09,11:02:00,NaN,11:05:00,11:15:00,NaN,YZJ,00:03:00,00:13:00,1,Yes,TCE,NaN,NaN
3441,2021-12-31 00:00:00,3A,3826,3.02105e+09,13:05:00,NaN,13:16:00,NaN,NaN,YSM,00:11:00,NaN,NaN,,NaN,NaN,NaN
3442,2021-12-31 00:00:00,3B,3610,3.02105e+09,15:10:00,NaN,15:25:00,NaN,NaN,DH,00:15:00,NaN,NaN,,NaN,NaN,NaN
3443,2021-12-31 00:00:00,3B,3605,3.02105e+09,16:26:00,NaN,16:32:00,NaN,NaN,DH,00:06:00,NaN,NaN,,NaN,NaN,NaN

## Export to CSV from Excel

In [129]:
#export to csv
df2.to_csv('merged_PEH_TTO_Data.csv', header=True,index=False)

# Data Cleaning

In [109]:
#read csv for further cleaning
df_csv = pd.read_csv('merged_PEH_TTO_Data.csv')
df_csv

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
0,15/3/21 0:00,4A,4825,302100869,13:50:00,NaN,13:53:00,NaN,,CHAR,0:03:00,NaN,NaN,NaN,NaN,NaN,NaN
1,11/5/21 0:00,4B,4606,302101606,8:35:00,NaN,8:49:00,9:00:00,Please help fill in PML Data,YSM,0:14:00,0:25:00,3,Yes,AT,No,MR not complete
2,26/8/21 0:00,3A,3841,302102993,12:32:00,NaN,12:39:00,NaN,,LLY,0:07:00,NaN,NaN,,NaN,NaN,NaN
3,3/10/21 0:00,3A,3838,302103523,11:37:00,NaN,11:43:00,NaN,,TFP,0:06:00,NaN,NaN,,NaN,NaN,NaN
4,16/10/21 0:00,3B,3616,302103680,9:19:00,NaN,9:39:00,NaN,,LLY,0:20:00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3269,27/10/21 0:00,3B,3609,NaN,8:30:00,NaN,8:48:00,NaN,,YSM,0:18:00,NaN,NaN,NaN,NaN,NaN,NaN
3270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN

In [110]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3273 entries, 0 to 3272
Data columns (total 17 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Date                                                          3246 non-null   object
 1   Ward                                                          3232 non-null   object
 2   Room                                                          3238 non-null   object
 3   Case Number                                                   3239 non-null   object
 4   Verified                                                      3243 non-null   object
 5   Meds Sent Down                                                313 non-null    object
 6   Checked                                                       3244 non-null   object
 7   Counselled                                                    993 non-null    object
 8   Remarks
(input paeds if it is a 4P patient in 4A)             2420 non-null   object
 9   Checked by Pharmacist                                         3238 non-null   object
 10  Time to Ready for Collection                                  3239 non-null   object
 11  Time to Counselling                                           989 non-null    object
 12  No. of Items                                                  985 non-null    object
 13  Bedside Counselling Candidate                                 2751 non-null   object
 14  Dispensed by                                                  990 non-null    object
 15  PML given?                                                    563 non-null    object
 16  If not given, WHY?! If given, were any interventions needed?  268 non-null    object
dtypes: object(17)
memory usage: 434.8+ KB

## Handle Missing Values

In [111]:
df_csv.notnull().sum()

Date                                                            3246
Ward                                                            3232
Room                                                            3238
Case Number                                                     3239
Verified                                                        3243
Meds Sent Down                                                   313
Checked                                                         3244
Counselled                                                       993
Remarks\n(input paeds if it is a 4P patient in 4A)              2420
Checked by Pharmacist                                           3238
Time to Ready for Collection                                    3239
Time to Counselling                                              989
No. of Items                                                     985
Bedside Counselling Candidate                                   2751
Dispensed by                                                     990
PML given?                                                       563
If not given, WHY?! If given, were any interventions needed?     268
dtype: int64

In [112]:
df_csv.isnull().sum()

Date                                                              27
Ward                                                              41
Room                                                              35
Case Number                                                       34
Verified                                                          30
Meds Sent Down                                                  2960
Checked                                                           29
Counselled                                                      2280
Remarks\n(input paeds if it is a 4P patient in 4A)               853
Checked by Pharmacist                                             35
Time to Ready for Collection                                      34
Time to Counselling                                             2284
No. of Items                                                    2288
Bedside Counselling Candidate                                    522
Dispensed by                                                    2283
PML given?                                                      2710
If not given, WHY?! If given, were any interventions needed?    3005
dtype: int64

### Empty Case Number

In [113]:
#What do 'Empty' Case Number means even if the system tracked a medication dispensed record?

df_csv[df_csv['Case Number'].isnull()]

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
3239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEND UP TTO AT 1200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3240,19/1/21 0:00,3A,3816,NaN,10:34:00,NaN,10:52:00,NaN,NaN,YSM,0:18:00,NaN,NaN,,NaN,NaN,NaN
3241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Please help fill in PML Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Please help fill in PML Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TTO sent up at 1240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3260,19/8/21 0:00,NaN,2002,NaN,12:25:00,NaN,12:38:00,NaN,,DH,0:13:00,NaN,NaN,,NaN,NaN,NaN
3261,19/8/21 0:00,NaN,NaN,NaN,15:00:00,NaN,15:07:00,NaN,,CHAR,0:07:00,NaN,NaN,,NaN,NaN,NaN
3262,20/8/21 0:00,NaN,NaN,NaN,0:00:00,NaN,9:22:00,9:40:00,,TCE,NaN,NaN,5,,DH,YES,NaN
3263,20/8/21 0:00,NaN,NaN,NaN,11:05:00,NaN,11:13:00,11:20:00,,LLY,0:08:00,0:15:00,3,,DH,NaN,NaN
3264,20/8/21 0:00,NaN,NaN,NaN,10:30:00,NaN,10:38:00,10:55:00,,DH,0:08:00,0:25:00,5,,DH,NaN,NaN
3265,20/8/21 0:00,NaN,NaN,NaN,9:25:00,NaN,9:33:00,9:41:00,,DH,0:08:00,0:16:00,NaN,,DH,NO,<24HR
3266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3269,27/10/21 0:00,3B,3609,NaN,8:30:00,NaN,8:48:00,NaN,,YSM,0:18:00,NaN,NaN,NaN,NaN,NaN,NaN
3270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN

In [114]:
df_csv = df_csv.dropna(subset=['Date'])

df_csv.isnull().sum()

Date                                                               0
Ward                                                              15
Room                                                               9
Case Number                                                        8
Verified                                                           4
Meds Sent Down                                                  2933
Checked                                                            3
Counselled                                                      2253
Remarks\n(input paeds if it is a 4P patient in 4A)               832
Checked by Pharmacist                                              9
Time to Ready for Collection                                       8
Time to Counselling                                             2257
No. of Items                                                    2261
Bedside Counselling Candidate                                    517
Dispensed by                                                    2256
PML given?                                                      2683
If not given, WHY?! If given, were any interventions needed?    2978
dtype: int64

## Data Standardization

### Rename Columns

In [115]:
#Rename Columns for future standardization
new_cols_name = {'Verified': 'Time TTO Received', 
                'Meds Sent Down': 'Time (Meds Sent Down)', 
                'Checked': 'Time TTO Checked', 
                'Counselled': 'Time (Counselled)', 
                'Remarks\n(input paeds if it is a 4P patient in 4A)': 'Remarks', 
                'Checked by Pharmacist': 'Checked By (Pharmacist)', 
                'Time to Ready for Collection': 'Time Taken (Ready for Collection)', 
                'Time to Counselling': 'Time Taken (to Counselling)', 
                'No. of Items': 'No. of Drugs'}

df_csv.rename(columns=new_cols_name, inplace=True)

df_csv.head()

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
0,15/3/21 0:00,4A,4825,302100869,13:50:00,NaN,13:53:00,NaN,,CHAR,0:03:00,NaN,NaN,NaN,NaN,NaN,NaN
1,11/5/21 0:00,4B,4606,302101606,8:35:00,NaN,8:49:00,9:00:00,Please help fill in PML Data,YSM,0:14:00,0:25:00,3,Yes,AT,No,MR not complete
2,26/8/21 0:00,3A,3841,302102993,12:32:00,NaN,12:39:00,NaN,,LLY,0:07:00,NaN,NaN,,NaN,NaN,NaN
3,3/10/21 0:00,3A,3838,302103523,11:37:00,NaN,11:43:00,NaN,,TFP,0:06:00,NaN,NaN,,NaN,NaN,NaN
4,16/10/21 0:00,3B,3616,302103680,9:19:00,NaN,9:39:00,NaN,,LLY,0:20:00,NaN,NaN,NaN,NaN,NaN,NaN

### Fix Data Type(s) for Time

In [116]:
#Change 'Date' Column to datetime
df_csv['Date'] = pd.to_datetime(df_csv['Date'], infer_datetime_format=True, errors='coerce')

<ipython-input-116-faa764c8f5fb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Date'] = pd.to_datetime(df_csv['Date'], infer_datetime_format=True, errors='coerce')

In [117]:
#Change 'Date' Column to datetime.dt.date
df_csv['Date'] = df_csv['Date'].dt.date

<ipython-input-117-0e72d1b2ae2b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Date'] = df_csv['Date'].dt.date

In [118]:
#Drop invalid Time (Case Number: 3021022234, 3021022185, 3021026234, 3021032879, 3021032837)
#Dropped externally as format do not fit

In [119]:
#Change 'Time TTO Received', 'Time (Meds Sent Down)', 'Time TTO Checked', 'Time (Counselled)'
#       'Time Taken (Ready for Collection)', 'Time Taken (to Counselling)' 
#       Columns to datetime.dt.time

df_csv['Time TTO Received'] = pd.to_datetime(df_csv['Time TTO Received'], format='%H:%M:%S').dt.time
df_csv['Time (Meds Sent Down)'] = pd.to_datetime(df_csv['Time (Meds Sent Down)'], format='%H:%M:%S').dt.time
df_csv['Time TTO Checked'] = pd.to_datetime(df_csv['Time TTO Checked'], format='%H:%M:%S').dt.time
df_csv['Time (Counselled)'] = pd.to_datetime(df_csv['Time (Counselled)'], format='%H:%M:%S').dt.time
df_csv['Time Taken (Ready for Collection)'] = pd.to_datetime(df_csv['Time Taken (Ready for Collection)'], format='%H:%M:%S').dt.time
df_csv['Time Taken (to Counselling)'] = pd.to_datetime(df_csv['Time Taken (to Counselling)'], format='%H:%M:%S').dt.time

<ipython-input-119-0958bc5bba9f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Time TTO Received'] = pd.to_datetime(df_csv['Time TTO Received'], format='%H:%M:%S').dt.time
<ipython-input-119-0958bc5bba9f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Time (Meds Sent Down)'] = pd.to_datetime(df_csv['Time (Meds Sent Down)'], format='%H:%M:%S').dt.time
<ipython-input-119-0958bc5bba9f>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Time TTO Checked'] = pd.to_datetime(df_csv['Time TTO Checked'], format='%H:%M:%S').dt.time
<ipython-input-119-0958bc5bba9f>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Time (Counselled)'] = pd.to_datetime(df_csv['Time (Counselled)'], format='%H:%M:%S').dt.time
<ipython-input-119-0958bc5bba9f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Time Taken (Ready for Collection)'] = pd.to_datetime(df_csv['Time Taken (Ready for Collection)'], format='%H:%M:%S').dt.time
<ipython-input-119-0958bc5bba9f>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Time Taken (to Counselling)'] = pd.to_datetime(df_csv['Time Taken (to Counselling)'], format='%H:%M:%S').dt.time

In [120]:
#Change 'NaT/NaN' to '00:00:00'

#df_csv['Time TTO Received'] = df_csv['Time TTO Received'].fillna(pd.Timedelta(seconds=0))
#df_csv['Time (Meds Sent Down)'] = df_csv['Time (Meds Sent Down)'].fillna(pd.Timedelta(seconds=0))
#df_csv['Time TTO Checked'] = df_csv['Time TTO Checked'].fillna(pd.Timedelta(seconds=0))
#df_csv['Time (Counselled)'] = df_csv['Time (Counselled)'].fillna(pd.Timedelta(seconds=0))
#df_csv['Time Taken (Ready for Collection)'] = df_csv['Time Taken (Ready for Collection)'].fillna(pd.Timedelta(seconds=0))
#df_csv['Time Taken (to Counselling)'] = df_csv['Time Taken (to Counselling)'].fillna(pd.Timedelta(seconds=0))

In [121]:
#Remove '0 days' in all Time data type

#df_csv['Time TTO Received'] = df_csv['Time TTO Received'].astype(str).str.split('0 days ').str[-1]
#df_csv['Time (Meds Sent Down)'] = df_csv['Time (Meds Sent Down)'].astype(str).str.split('0 days ').str[-1]
#df_csv['Time TTO Checked'] = df_csv['Time TTO Checked'].astype(str).str.split('0 days ').str[-1]
#df_csv['Time (Counselled)'] = df_csv['Time (Counselled)'].astype(str).str.split('0 days ').str[-1]
#df_csv['Time Taken (Ready for Collection)'] = df_csv['Time Taken (Ready for Collection)'].astype(str).str.split('0 days ').str[-1]
#df_csv['Time Taken (to Counselling)'] = df_csv['Time Taken (to Counselling)'].astype(str).str.split('0 days ').str[-1]

In [122]:
#reinstate into Time format again

#df_csv['Time TTO Received'] = pd.to_datetime(df_csv['Time TTO Received'], format='%H:%M:%S').dt.time
#df_csv['Time (Meds Sent Down)'] = pd.to_datetime(df_csv['Time (Meds Sent Down)'], format='%H:%M:%S').dt.time
#df_csv['Time TTO Checked'] = pd.to_datetime(df_csv['Time TTO Checked'], format='%H:%M:%S').dt.time
#df_csv['Time (Counselled)'] = pd.to_datetime(df_csv['Time (Counselled)'], format='%H:%M:%S').dt.time
#df_csv['Time Taken (Ready for Collection)'] = pd.to_datetime(df_csv['Time Taken (Ready for Collection)'], format='%H:%M:%S').dt.time
#df_csv['Time Taken (to Counselling)'] = pd.to_datetime(df_csv['Time Taken (to Counselling)'], format='%H:%M:%S').dt.time

In [123]:
df_csv.head()

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
0,2021-03-15,4A,4825,302100869,13:50:00,NaT,13:53:00,NaT,,CHAR,00:03:00,NaT,NaN,NaN,NaN,NaN,NaN
1,2021-11-05,4B,4606,302101606,08:35:00,NaT,08:49:00,09:00:00,Please help fill in PML Data,YSM,00:14:00,00:25:00,3,Yes,AT,No,MR not complete
2,2021-08-26,3A,3841,302102993,12:32:00,NaT,12:39:00,NaT,,LLY,00:07:00,NaT,NaN,,NaN,NaN,NaN
3,2021-03-10,3A,3838,302103523,11:37:00,NaT,11:43:00,NaT,,TFP,00:06:00,NaT,NaN,,NaN,NaN,NaN
4,2021-10-16,3B,3616,302103680,09:19:00,NaT,09:39:00,NaT,,LLY,00:20:00,NaT,NaN,NaN,NaN,NaN,NaN

### Fix NaN values in non-Time Data Type

In [124]:
#No. of Drugs 
df_csv['No. of Drugs'] = df_csv['No. of Drugs'].fillna("NA")

<ipython-input-124-a32946b9d8b4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['No. of Drugs'] = df_csv['No. of Drugs'].fillna("NA")

In [125]:
#Bedside Counselling Candidate
df_csv['Bedside Counselling Candidate'] = df_csv['Bedside Counselling Candidate'].fillna('No')

#IF Time Taken (to Counselling) == 00:00:00, then Bedside Counselling Candidate = No
df_csv.loc[(df_csv['Time Taken (to Counselling)'] == pd.to_datetime('00:00:00').time()), 'Bedside Counselling Candidate'] = "No"

#IF Time (to Counselling) > 00:00:00, then Bedside Counselling Candidate = Yes
df_csv.loc[(df_csv['Time Taken (to Counselling)'] > pd.to_datetime('00:00:00').time()), 'Bedside Counselling Candidate'] = "Yes"

<ipython-input-125-275bbb8e5e20>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Bedside Counselling Candidate'] = df_csv['Bedside Counselling Candidate'].fillna('No')
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
<ipython-input-125-275bbb8e5e20>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv.loc[(df_csv['Time Taken (to Counselling)'] == pd.to_datetime('00:00:00').time()), 'Bedside Counselling Candidate'] = "No"
<ipython-input-125-275bbb8e5e20>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv.loc[(df_csv['Time Taken (to Counselling)'] > pd.to_datetime('00:00:00').time()), 'Bedside Counselling Candidate'] = "Yes"

In [126]:
df_csv.isnull().sum()

Date                                                               1
Ward                                                              15
Room                                                               9
Case Number                                                        8
Time TTO Received                                                  4
Time (Meds Sent Down)                                           2933
Time TTO Checked                                                   3
Time (Counselled)                                               2253
Remarks                                                          832
Checked By (Pharmacist)                                            9
Time Taken (Ready for Collection)                                  8
Time Taken (to Counselling)                                     2257
No. of Drugs                                                       0
Bedside Counselling Candidate                                      0
Dispensed by                                                    2256
PML given?                                                      2683
If not given, WHY?! If given, were any interventions needed?    2978
dtype: int64

In [127]:
# Fill all NA with empty string

#dfinal = df_csv.fillna('')
#dfinal

In [128]:
dfinal = df_csv

# EDA

## Day of Week

In [129]:
dfinal['Weekday'] = pd.to_datetime(dfinal['Date']).dt.day_name()

#Fill NaN with empty string for those without a Date
dfinal['Weekday'] = dfinal['Weekday'].fillna('')

dfinal.head()

<ipython-input-129-8bf322f56c0f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Weekday'] = pd.to_datetime(dfinal['Date']).dt.day_name()
<ipython-input-129-8bf322f56c0f>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Weekday'] = dfinal['Weekday'].fillna('')

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?",Weekday
0,2021-03-15,4A,4825,302100869,13:50:00,NaT,13:53:00,NaT,,CHAR,00:03:00,NaT,NA,No,NaN,NaN,NaN,Monday
1,2021-11-05,4B,4606,302101606,08:35:00,NaT,08:49:00,09:00:00,Please help fill in PML Data,YSM,00:14:00,00:25:00,3,Yes,AT,No,MR not complete,Friday
2,2021-08-26,3A,3841,302102993,12:32:00,NaT,12:39:00,NaT,,LLY,00:07:00,NaT,NA,,NaN,NaN,NaN,Thursday
3,2021-03-10,3A,3838,302103523,11:37:00,NaT,11:43:00,NaT,,TFP,00:06:00,NaT,NA,,NaN,NaN,NaN,Wednesday
4,2021-10-16,3B,3616,302103680,09:19:00,NaT,09:39:00,NaT,,LLY,00:20:00,NaT,NA,No,NaN,NaN,NaN,Saturday

## Time TTO Dispensed 

PEH does not have a Time TTO Dispensed indicator in their original raw dataset

In [130]:
#IF time counselled > time checked : time dispensed == time counselled
#else time dispensed == time checked

dfinal['Time TTO Dispensed'] = np.where((dfinal['Time (Counselled)'] > dfinal['Time TTO Checked']), 
                                        dfinal['Time (Counselled)'], dfinal['Time TTO Checked'])

dfinal.head()

<ipython-input-130-84effe38d11b>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Time TTO Dispensed'] = np.where((dfinal['Time (Counselled)'] > dfinal['Time TTO Checked']),

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?",Weekday,Time TTO Dispensed
0,2021-03-15,4A,4825,302100869,13:50:00,NaT,13:53:00,NaT,,CHAR,00:03:00,NaT,NA,No,NaN,NaN,NaN,Monday,13:53:00
1,2021-11-05,4B,4606,302101606,08:35:00,NaT,08:49:00,09:00:00,Please help fill in PML Data,YSM,00:14:00,00:25:00,3,Yes,AT,No,MR not complete,Friday,09:00:00
2,2021-08-26,3A,3841,302102993,12:32:00,NaT,12:39:00,NaT,,LLY,00:07:00,NaT,NA,,NaN,NaN,NaN,Thursday,12:39:00
3,2021-03-10,3A,3838,302103523,11:37:00,NaT,11:43:00,NaT,,TFP,00:06:00,NaT,NA,,NaN,NaN,NaN,Wednesday,11:43:00
4,2021-10-16,3B,3616,302103680,09:19:00,NaT,09:39:00,NaT,,LLY,00:20:00,NaT,NA,No,NaN,NaN,NaN,Saturday,09:39:00

## Overall Time Taken

In [131]:
dfinal['Overall Time Taken (mins)'] = np.where(
                                                (dfinal['Time Taken (to Counselling)'].isnull()), 
                                                pd.to_datetime(dfinal['Time Taken (Ready for Collection)'].astype(str)).dt.minute, 
                                                pd.to_datetime(dfinal['Time Taken (to Counselling)'].astype(str)).dt.minute)

dfinal.head()

<ipython-input-131-3b5ce0199fd7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Overall Time Taken (mins)'] = np.where(

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?",Weekday,Time TTO Dispensed,Overall Time Taken (mins)
0,2021-03-15,4A,4825,302100869,13:50:00,NaT,13:53:00,NaT,,CHAR,00:03:00,NaT,NA,No,NaN,NaN,NaN,Monday,13:53:00,3.0
1,2021-11-05,4B,4606,302101606,08:35:00,NaT,08:49:00,09:00:00,Please help fill in PML Data,YSM,00:14:00,00:25:00,3,Yes,AT,No,MR not complete,Friday,09:00:00,25.0
2,2021-08-26,3A,3841,302102993,12:32:00,NaT,12:39:00,NaT,,LLY,00:07:00,NaT,NA,,NaN,NaN,NaN,Thursday,12:39:00,7.0
3,2021-03-10,3A,3838,302103523,11:37:00,NaT,11:43:00,NaT,,TFP,00:06:00,NaT,NA,,NaN,NaN,NaN,Wednesday,11:43:00,6.0
4,2021-10-16,3B,3616,302103680,09:19:00,NaT,09:39:00,NaT,,LLY,00:20:00,NaT,NA,No,NaN,NaN,NaN,Saturday,09:39:00,20.0

In [132]:
#pd.set_option('display.max_columns', None)
dfinal[dfinal['Time Taken (to Counselling)'].notnull()]

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?",Weekday,Time TTO Dispensed,Overall Time Taken (mins)
1,2021-11-05,4B,4606,302101606,08:35:00,NaT,08:49:00,09:00:00,Please help fill in PML Data,YSM,00:14:00,00:25:00,3,Yes,AT,No,MR not complete,Friday,09:00:00,25.0
24,2021-01-19,4A,4810,3020043322,09:27:00,NaT,09:35:00,09:50:00,WAITED FOR CAREGIVER DISPENSED AT 12:30,YZJ,00:08:00,00:23:00,5,Yes,YZJ,NaN,NaN,Tuesday,09:50:00,23.0
25,2021-06-01,3B,3605,3020043353,08:45:00,NaT,09:00:00,09:25:00,NaN,TFP,00:15:00,00:40:00,2,Yes,TFP,NaN,NaN,Tuesday,09:25:00,40.0
33,2021-06-01,4B,4609,3020044283,11:10:00,NaT,11:18:00,11:27:00,NaN,TFP,00:08:00,00:17:00,3,Yes,TFP,NaN,NaN,Tuesday,11:27:00,17.0
38,2021-05-01,4A,4809,3021000006,09:55:00,NaT,09:59:00,10:05:00,NaN,DH,00:04:00,00:10:00,1,Yes,LLY,NaN,NaN,Saturday,10:05:00,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3233,2021-01-13,4B,4613,30210001061,08:35:00,NaT,08:50:00,08:56:00,NaN,AT,00:15:00,00:21:00,2,Yes,AT,NaN,NaN,Wednesday,08:56:00,21.0
3235,2021-05-08,3B,3614,30210267925,09:30:00,NaT,10:06:00,10:15:00,,AT,00:36:00,00:45:00,8,Yes,AT,NaN,NaN,Saturday,10:15:00,45.0
3263,2021-08-20,NaN,NaN,NaN,11:05:00,NaT,11:13:00,11:20:00,,LLY,00:08:00,00:15:00,3,Yes,DH,NaN,NaN,Friday,11:20:00,15.0
3264,2021-08-20,NaN,NaN,NaN,10:30:00,NaT,10:38:00,10:55:00,,DH,00:08:00,00:25:00,5,Yes,DH,NaN,NaN,Friday,10:55:00,25.0
3265,2021-08-20,NaN,NaN,NaN,09:25:00,NaT,09:33:00,09:41:00,,DH,00:08:00,00:16:00,NA,Yes,DH,NO,<24HR,Friday,09:41:00,16.0

In [133]:
#Time TTO Dispensed - Time (Counselled) - Time TTO Checked - Time (Meds Sent Down) - Time TTO Received

#IF Time (Counselled) != 00:00:00 & IF Time (Meds Sent Down) != 00:00:00, Subtract all from Time TTO Dispensed
#IF Time (Counselled) == 00:00:00 & Time (Meds Sent Down) == 00:00:00, Time TTO Dispensed - Time TTO Checked - Time TTO Received
#IF Time (Counselled) == 00:00:00 & Time (Meds Sent Down) != 00:00:00, Time TTO Dispensed - Time TTO Checked - Time (Meds Sent Down) - Time TTO Received
#IF Time (Counselled) != 00:00:00 & Time (Meds Sent Down) == 00:00:00, Time TTO Dispensed - Time (Counselled) - Time TTO Checked - Time TTO Received

#df_test = dfinal
#
#df_test['Overall Time Taken to Dispensed'] = np.where(  
#                                                    (df_test['Time (Counselled)'] != pd.to_datetime('00:00:00').time()) & 
#                                                    (df_test['Time (Meds Sent Down)'] != pd.to_datetime('00:00:00').time()),
#                                                        (pd.to_timedelta(df_test['Time TTO Dispensed'].astype(str)) 
#                                                        - pd.to_timedelta(df_test['Time (Counselled)'].astype(str)) 
#                                                        - pd.to_timedelta(df_test['Time TTO Checked'].astype(str)) 
#                                                        - pd.to_timedelta(df_test['Time (Meds Sent Down)'].astype(str)) 
#                                                        - pd.to_timedelta(df_test['Time TTO Received'].astype(str))) ,
#                                                        
#                                                    np.where(
#                                                        (df_test['Time (Counselled)'] == pd.to_datetime('00:00:00').time()) & 
#                                                        (df_test['Time (Meds Sent Down)'] == pd.to_datetime('00:00:00').time()),
#                                                            (pd.to_timedelta(df_test['Time TTO Dispensed'].astype(str))                                     
#                                                            - pd.to_timedelta(df_test['Time TTO Checked'].astype(str))                                                            
#                                                            - pd.to_timedelta(df_test['Time TTO Received'].astype(str))) ,
#
#                                                    np.where(
#                                                        (df_test['Time (Counselled)'] == pd.to_datetime('00:00:00').time()) & 
#                                                        (df_test['Time (Meds Sent Down)'] != pd.to_datetime('00:00:00').time()),
#                                                            (pd.to_timedelta(df_test['Time TTO Dispensed'].astype(str))                                                             
#                                                            - pd.to_timedelta(df_test['Time TTO Checked'].astype(str)) 
#                                                            - pd.to_timedelta(df_test['Time (Meds Sent Down)'].astype(str)) 
#                                                            - pd.to_timedelta(df_test['Time TTO Received'].astype(str))) ,
#
#                                                    np.where(
#                                                        (df_test['Time (Counselled)'] != pd.to_datetime('00:00:00').time()) & 
#                                                        (df_test['Time (Meds Sent Down)'] == pd.to_datetime('00:00:00').time()),
#                                                            (pd.to_timedelta(df_test['Time TTO Dispensed'].astype(str)) 
#                                                            - pd.to_timedelta(df_test['Time (Counselled)'].astype(str)) 
#                                                            - pd.to_timedelta(df_test['Time TTO Checked'].astype(str))                                                             
#                                                            - pd.to_timedelta(df_test['Time TTO Received'].astype(str))) , 
#
#                                                            np.NaN))))
#
#                                                            
#df_test

#dfinal['Overall Time Taken to Dispensed'] = (pd.to_timedelta(dfinal['Time TTO Dispensed'].astype(str)) 
#                                            - pd.to_timedelta(dfinal['Time (Counselled)'].astype(str)) 
#                                            - pd.to_timedelta(dfinal['Time TTO Checked'].astype(str)) 
#                                            - pd.to_timedelta(dfinal['Time (Meds Sent Down)'].astype(str)) 
#                                            - pd.to_timedelta(dfinal['Time TTO Received'].astype(str)))

In [134]:
#def td_to_hmsstr(td):
#    """
#    convert a timedelta object td to a string in HH:MM:SS format.
#    """
#    hours, remainder = divmod(td.total_seconds(), 3600)
#    minutes, seconds = divmod(remainder, 60)
#    return f'{int(hours):02}:{int(minutes):02}:{int(seconds):02}'
#
#
#df_test['Overall Time Taken to Dispensed'] = df_test['Overall Time Taken to Dispensed'].apply(td_to_hmsstr)
#df_test

## Meet KPI?

GEH: Total Time Taken < 45mins = Yes, else: No.

In [135]:
dfinal['Meet KPI'] = np.where((dfinal['Overall Time Taken (mins)'].isnull()), "NA",
                            np.where((dfinal['Overall Time Taken (mins)'] <= (pd.to_datetime('00:45:00')).minute),
                                    'Yes', 'No'))

dfinal

<ipython-input-135-7d5cb19040d2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Meet KPI'] = np.where((dfinal['Overall Time Taken (mins)'].isnull()), "NA",

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?",Weekday,Time TTO Dispensed,Overall Time Taken (mins),Meet KPI
0,2021-03-15,4A,4825,302100869,13:50:00,NaT,13:53:00,NaT,,CHAR,00:03:00,NaT,NA,No,NaN,NaN,NaN,Monday,13:53:00,3.0,Yes
1,2021-11-05,4B,4606,302101606,08:35:00,NaT,08:49:00,09:00:00,Please help fill in PML Data,YSM,00:14:00,00:25:00,3,Yes,AT,No,MR not complete,Friday,09:00:00,25.0,Yes
2,2021-08-26,3A,3841,302102993,12:32:00,NaT,12:39:00,NaT,,LLY,00:07:00,NaT,NA,,NaN,NaN,NaN,Thursday,12:39:00,7.0,Yes
3,2021-03-10,3A,3838,302103523,11:37:00,NaT,11:43:00,NaT,,TFP,00:06:00,NaT,NA,,NaN,NaN,NaN,Wednesday,11:43:00,6.0,Yes
4,2021-10-16,3B,3616,302103680,09:19:00,NaT,09:39:00,NaT,,LLY,00:20:00,NaT,NA,No,NaN,NaN,NaN,Saturday,09:39:00,20.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3262,2021-08-20,NaN,NaN,NaN,00:00:00,NaT,09:22:00,09:40:00,,TCE,NaT,NaT,5,,DH,YES,NaN,Friday,09:40:00,NaN,NA
3263,2021-08-20,NaN,NaN,NaN,11:05:00,NaT,11:13:00,11:20:00,,LLY,00:08:00,00:15:00,3,Yes,DH,NaN,NaN,Friday,11:20:00,15.0,Yes
3264,2021-08-20,NaN,NaN,NaN,10:30:00,NaT,10:38:00,10:55:00,,DH,00:08:00,00:25:00,5,Yes,DH,NaN,NaN,Friday,10:55:00,25.0,Yes
3265,2021-08-20,NaN,NaN,NaN,09:25:00,NaT,09:33:00,09:41:00,,DH,00:08:00,00:16:00,NA,Yes,DH,NO,<24HR,Friday,09:41:00,16.0,Yes
3269,2021-10-27,3B,3609,NaN,08:30:00,NaT,08:48:00,NaT,,YSM,00:18:00,NaT,NA,No,NaN,NaN,NaN,Wednesday,08:48:00,18.0,Yes

In [136]:
dfinal[dfinal['Meet KPI']=="No"]

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?",Weekday,Time TTO Dispensed,Overall Time Taken (mins),Meet KPI
205,2021-01-26,3B,3609,3021002242,09:25:00,09:36:00,09:55:00,10:35:00,NaN,YSM,00:19:00,00:59:00,4,Yes,CHAR,NaN,NaN,Tuesday,10:35:00,59.0,No
221,2021-01-25,4B,4612,3021002435,08:53:00,NaT,08:55:00,10:50:00,NaN,DH,00:02:00,01:57:00,6,Yes,DH,NaN,NaN,Monday,10:50:00,57.0,No
229,2021-01-26,3B,3610,3021002640,09:00:00,09:36:00,10:00:00,10:35:00,NaN,YSM,00:24:00,00:59:00,1,Yes,CHAR,NaN,NaN,Tuesday,10:35:00,59.0,No
518,2021-02-25,3B,3606,3021006433,09:13:00,09:30:00,09:58:00,10:16:00,NaN,CHAR,00:28:00,00:46:00,7,Yes,CHAR,NaN,NaN,Thursday,10:16:00,46.0,No
544,2021-05-03,3B,3606,3021006885,09:30:00,09:42:00,10:25:00,10:30:00,,TFP,00:43:00,00:48:00,6,Yes,TFP,NaN,NaN,Monday,10:30:00,48.0,No
787,2021-03-25,4B,4605,3021010026,09:44:00,NaT,10:08:00,10:40:00,Please help fill in PML Data,YSM,00:24:00,00:56:00,3,Yes,LLY,Yes,NaN,Thursday,10:40:00,56.0,No
1250,2021-10-05,DAY,2011,3021016241,11:31:00,NaT,12:23:00,NaT,,YSL,00:52:00,NaT,NA,,NaN,NaN,NaN,Tuesday,12:23:00,52.0,No
1324,2021-05-20,3A,3841,3021017176,20:35:00,NaT,21:26:00,NaT,Checked by duty manager,ANC SITI,00:51:00,NaT,NA,,NaN,NaN,NaN,Thursday,21:26:00,51.0,No
1331,2021-05-19,4B,4619,3021017254,10:00:00,NaT,10:50:00,NaT,passed to SN,DH,00:50:00,NaT,NA,No,NaN,NaN,NaN,Wednesday,10:50:00,50.0,No
1345,2021-05-21,4A,4806,3021017474,08:45:00,NaT,08:54:00,09:37:00,,DH,00:09:00,00:52:00,3,Yes,DH,NaN,NaN,Friday,09:37:00,52.0,No
1469,2021-09-06,4A,4803,3021019527,08:05:00,NaT,08:35:00,08:52:00,,TCE,00:30:00,00:47:00,1,Yes,YZJ,NaN,NaN,Monday,08:52:00,47.0,No
1495,2021-06-14,3B,3609,3021019988,09:20:00,NaT,09:55:00,10:10:00,,AT,00:35:00,00:50:00,6,Yes,AT,NaN,NaN,Monday,10:10:00,50.0,No
1599,2021-06-25,4A,4808,3021021292,08:30:00,NaT,08:51:00,09:20:00,,YSM,00:21:00,00:50:00,3,Yes,YZJ,NaN,NaN,Friday,09:20:00,50.0,No
1666,2021-02-07,4B,4607,3021022392,07:58:00,NaT,08:18:00,08:50:00,Please help fill in PML Data,YSM,00:20:00,00:52:00,6,Yes,TFP,Yes,NaN,Sunday,08:50:00,52.0,No
1779,2021-07-21,3A,3817,3021024708,07:10:00,NaT,08:09:00,NaT,,CHAR,00:59:00,NaT,NA,,NaN,NaN,NaN,Wednesday,08:09:00,59.0,No
1817,2021-07-29,4B,4603,3021025398,07:54:00,NaT,08:10:00,08:45:00,Please help fill in PML Data,TFP,00:16:00,00:51:00,5,Yes,TFP,Yes,NaN,Thursday,08:45:00,51.0,No
1825,2021-07-28,4B,4610,3021025568,07:49:00,07:55:00,08:14:00,08:45:00,Please help fill in PML Data,YSM,00:19:00,00:50:00,3,Yes,YZJ,YES,NaN,Wednesday,08:45:00,50.0,No
2040,2021-08-27,4B,4616,3021029415,08:04:00,NaT,08:37:00,09:00:00,Please help fill in PML Data,YSM,00:33:00,00:56:00,6,Yes,LLY,YES,NaN,Friday,09:00:00,56.0,No
2057,2021-08-26,4B,4603,3021029580,09:09:00,NaT,09:34:00,09:59:00,Please help fill in PML Data,TFP,00:25:00,00:50:00,1,Yes,LLY,NO,Unable to contact both doctors in charge - bot...,Thursday,09:59:00,50.0,No
2060,2021-08-24,3B,3605,3021029626,10:44:00,NaT,11:22:00,11:35:00,,LLY,00:38:00,00:51:00,4,Yes,LLY,NaN,NaN,Tuesday,11:35:00,51.0,No
2154,2021-05-09,4A,4817,3021030961,10:45:00,NaT,11:31:00,NaT,,LLY,00:46:00,NaT,NA,No,NaN,NaN,NaN,Sunday,11:31:00,46.0,No
2194,2021-05-09,3A,3815,3021031288,10:37:00,NaT,11:33:00,NaT,,LLY,00:56:00,NaT,NA,No,NaN,NaN,NaN,Sunday,11:33:00,56.0,No
2240,2021-09-20,3A,3822,3021031932,09:30:00,NaT,11:20:00,NaT,ALENDRONATE,TFP,01:50:00,NaT,NA,No,NaN,NaN,NaN,Monday,11:20:00,50.0,No
2260,2021-09-13,4B,4607,3021032074,09:28:00,NaT,09:45:00,10:15:00,Please help fill in PML Data,TCE,00:17:00,00:47:00,7,Yes,TCE,NO,NaN,Monday,10:15:00,47.0,No
2346,2021-09-17,3A,3819,3021033135,18:45:00,NaT,19:35:00,NaT,,TFP,00:50:00,NaT,NA,,NaN,NaN,NaN,Friday,19:35:00,50.0,No
2727,2021-10-30,3B,3618,3021038997,12:50:00,NaT,13:47:00,NaT,,LLY,00:57:00,NaT,NA,No,NaN,NaN,NaN,Saturday,13:47:00,57.0,No
2759,2021-03-11,3B,3618,3021039550,08:00:00,NaT,08:05:00,08:50:00,,TFP,00:05:00,00:50:00,2,Yes,TFP,NaN,NaN,Thursday,08:50:00,50.0,No
2782,2021-05-11,3B,3605,3021039911,08:00:00,09:40:00,10:12:00,10:32:00,,DH,00:32:00,00:52:00,3,Yes,TFP,NaN,NaN,Tuesday,10:32:00,52.0,No
2831,2021-11-11,3B,3612,3021040740,09:57:00,NaT,10:37:00,10:45:00,,TCE,00:40:00,00:48:00,1,Yes,TCE,NaN,NaN,Thursday,10:45:00,48.0,No
2973,2021-01-12,3B,3605,3021043241,12:02:00,NaT,13:01:00,NaT,NaN,LLY,00:59:00,NaT,NA,,NaN,NaN,NaN,Tuesday,13:01:00,59.0,No
2989,2021-01-12,3B,3606,3021043487,12:07:00,NaT,13:03:00,NaT,NaN,LLY,00:56:00,NaT,NA,,NaN,NaN,NaN,Tuesday,13:03:00,56.0,No
2995,2021-12-22,3B,3603,3021043609,09:30:00,NaT,09:50:00,10:24:00,,LLY,00:20:00,00:54:00,1,Yes,TFP,NaN,NaN,Wednesday,10:24:00,54.0,No
3089,2021-12-17,3B,3609,3021045341,09:01:00,NaT,09:25:00,09:53:00,,TCE,00:24:00,00:52:00,10,Yes,TCE,NaN,NaN,Friday,09:53:00,52.0,No

## Office Hours

Standard Office Hours: 8:30AM to 5:00PM

In [137]:
dfinal['Office Hours'] = np.where(dfinal['Time TTO Received'].isnull() | dfinal['Time TTO Dispensed'].isnull() , 'NA',
                            np.where(  ((dfinal['Time TTO Received'] >= pd.to_datetime('08:30:00').time()) & 
                                        (dfinal['Time TTO Dispensed'] <= pd.to_datetime('17:00:00').time())),
                                        'Yes', 'No'))

dfinal

<ipython-input-137-2eb1a4e3b32b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Office Hours'] = np.where(dfinal['Time TTO Received'].isnull() | dfinal['Time TTO Dispensed'].isnull() , 'NA',

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?",Weekday,Time TTO Dispensed,Overall Time Taken (mins),Meet KPI,Office Hours
0,2021-03-15,4A,4825,302100869,13:50:00,NaT,13:53:00,NaT,,CHAR,00:03:00,NaT,NA,No,NaN,NaN,NaN,Monday,13:53:00,3.0,Yes,Yes
1,2021-11-05,4B,4606,302101606,08:35:00,NaT,08:49:00,09:00:00,Please help fill in PML Data,YSM,00:14:00,00:25:00,3,Yes,AT,No,MR not complete,Friday,09:00:00,25.0,Yes,Yes
2,2021-08-26,3A,3841,302102993,12:32:00,NaT,12:39:00,NaT,,LLY,00:07:00,NaT,NA,,NaN,NaN,NaN,Thursday,12:39:00,7.0,Yes,Yes
3,2021-03-10,3A,3838,302103523,11:37:00,NaT,11:43:00,NaT,,TFP,00:06:00,NaT,NA,,NaN,NaN,NaN,Wednesday,11:43:00,6.0,Yes,Yes
4,2021-10-16,3B,3616,302103680,09:19:00,NaT,09:39:00,NaT,,LLY,00:20:00,NaT,NA,No,NaN,NaN,NaN,Saturday,09:39:00,20.0,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3262,2021-08-20,NaN,NaN,NaN,00:00:00,NaT,09:22:00,09:40:00,,TCE,NaT,NaT,5,,DH,YES,NaN,Friday,09:40:00,NaN,NA,No
3263,2021-08-20,NaN,NaN,NaN,11:05:00,NaT,11:13:00,11:20:00,,LLY,00:08:00,00:15:00,3,Yes,DH,NaN,NaN,Friday,11:20:00,15.0,Yes,Yes
3264,2021-08-20,NaN,NaN,NaN,10:30:00,NaT,10:38:00,10:55:00,,DH,00:08:00,00:25:00,5,Yes,DH,NaN,NaN,Friday,10:55:00,25.0,Yes,Yes
3265,2021-08-20,NaN,NaN,NaN,09:25:00,NaT,09:33:00,09:41:00,,DH,00:08:00,00:16:00,NA,Yes,DH,NO,<24HR,Friday,09:41:00,16.0,Yes,Yes
3269,2021-10-27,3B,3609,NaN,08:30:00,NaT,08:48:00,NaT,,YSM,00:18:00,NaT,NA,No,NaN,NaN,NaN,Wednesday,08:48:00,18.0,Yes,Yes

In [138]:
dfinal[dfinal['Office Hours'] == 'No']

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?",Weekday,Time TTO Dispensed,Overall Time Taken (mins),Meet KPI,Office Hours
5,2021-05-11,3B,3614,302104046,17:52:00,NaT,17:57:00,NaT,,DH,00:05:00,NaT,NA,,NaN,NaN,NaN,Tuesday,17:57:00,5.0,Yes,No
145,2021-03-03,3A,3817,3021001379,08:20:00,NaT,08:38:00,NaT,,TFP,00:18:00,NaT,NA,,NaN,NaN,NaN,Wednesday,08:38:00,18.0,Yes,No
323,2021-04-02,4A,4822,3021003868,08:22:00,NaT,08:30:00,08:46:00,NaN,TFP,00:08:00,00:24:00,4,Yes,LLY,NaN,NaN,Friday,08:46:00,24.0,Yes,No
392,2021-04-03,4B,4613,3021004952,16:55:00,NaT,17:03:00,NaT,Please help fill in PML Data,TFP,00:08:00,NaT,NA,,NaN,Yes,NaN,Saturday,17:03:00,8.0,Yes,No
427,2021-02-17,4A,4808,3021005424,08:27:00,NaT,08:40:00,08:44:00,NaN,AT,00:13:00,00:17:00,3,Yes,TCE,NaN,NaN,Wednesday,08:44:00,17.0,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3220,2021-12-30,3B,3611,3021047321,08:00:00,09:50:00,10:08:00,10:17:00,NaN,TCE,00:18:00,00:27:00,7,Yes,TCE,NaN,NaN,Thursday,10:17:00,27.0,Yes,No
3225,2021-12-31,3A,3818,3021047351,08:12:00,NaT,08:20:00,NaT,NaN,TCE,00:08:00,NaT,NA,,NaN,NaN,NaN,Friday,08:20:00,8.0,Yes,No
3236,2021-10-10,3A,3829,AK,18:39:00,NaT,18:41:00,NaT,,CHAR,00:02:00,NaT,NA,,NaN,NaN,NaN,Sunday,18:41:00,2.0,Yes,No
3238,2021-08-19,NaN,NaN,dd,00:00:00,NaT,14:08:00,NaT,,CHAR,NaT,NaT,NA,,NaN,NaN,NaN,Thursday,14:08:00,NaN,NA,No
3262,2021-08-20,NaN,NaN,NaN,00:00:00,NaT,09:22:00,09:40:00,,TCE,NaT,NaT,5,,DH,YES,NaN,Friday,09:40:00,NaN,NA,No

# Export CLEANED to csv

In [139]:
#export to csv
dfinal.to_csv('PEH_CLEANED_Data.csv', header=True, index=False)