In [6]:
#Combining all Excel sheets into one --Assuming all have the same headers

import pandas as pd

f = '../PEH TTO Data.xlsx'
df = pd.read_excel(f, sheet_name=None)
df2 = pd.concat(df, ignore_index=True)

df2.head()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,2021-01-04 00:00:00,4A,4811,3.021e+09,09:52:00,NaN,10:00:00,10:10:00,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-04 00:00:00,3A,3828,3.02004e+09,08:34:00,NaN,08:44:00,NaN,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-04 00:00:00,3B,3606,3.021e+09,09:15:00,09:40:00,09:50:00,09:55:00,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-04 00:00:00,DAY,2011,3.021e+09,10:09:00,NaN,10:20:00,NaN,NaN,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-01-04 00:00:00,4B,4610,3.02004e+09,08:37:00,NaN,08:47:00,NaN,PATIENT FOR HOME ON WED,YSM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#drop unnecessary columns --unnamed
df2.drop(df2.columns[df2.columns.str.contains('Unnamed')], axis=1, inplace=True)
df2.head()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
0,2021-01-04 00:00:00,4A,4811,3.021e+09,09:52:00,NaN,10:00:00,10:10:00,NaN,TFP,00:08:00,00:18:00,3,Yes,TFP,NaN,NaN
1,2021-01-04 00:00:00,3A,3828,3.02004e+09,08:34:00,NaN,08:44:00,NaN,NaN,TFP,00:10:00,NaN,NaN,,NaN,NaN,NaN
2,2021-01-04 00:00:00,3B,3606,3.021e+09,09:15:00,09:40:00,09:50:00,09:55:00,NaN,TFP,00:10:00,00:15:00,2,Yes,TFP,NaN,NaN
3,2021-01-04 00:00:00,DAY,2011,3.021e+09,10:09:00,NaN,10:20:00,NaN,NaN,TFP,00:11:00,NaN,NaN,,NaN,NaN,NaN
4,2021-01-04 00:00:00,4B,4610,3.02004e+09,08:37:00,NaN,08:47:00,NaN,PATIENT FOR HOME ON WED,YSM,00:10:00,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3450 entries, 0 to 3449
Data columns (total 17 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Date                                                          3251 non-null   object
 1   Ward                                                          3237 non-null   object
 2   Room                                                          3243 non-null   object
 3   Case Number                                                   3244 non-null   object
 4   Verified                                                      3248 non-null   object
 5   Meds Sent Down                                                318 non-null    object
 6   Checked                                                       3249 non-null   object
 7   Counselled                                                    996 non-null    object
 8   Remarks
(input paeds if it is a 4P patient in 4A)             2425 non-null   object
 9   Checked by Pharmacist                                         3243 non-null   object
 10  Time to Ready for Collection                                  3244 non-null   object
 11  Time to Counselling                                           992 non-null    object
 12  No. of Items                                                  988 non-null    object
 13  Bedside Counselling Candidate                                 2759 non-null   object
 14  Dispensed by                                                  993 non-null    object
 15  PML given?                                                    563 non-null    object
 16  If not given, WHY?! If given, were any interventions needed?  268 non-null    object
dtypes: object(17)
memory usage: 458.3+ KB

In [9]:
df2.dropna(axis = 0, how = 'all', inplace = True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3281 entries, 0 to 3449
Data columns (total 17 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Date                                                          3251 non-null   object
 1   Ward                                                          3237 non-null   object
 2   Room                                                          3243 non-null   object
 3   Case Number                                                   3244 non-null   object
 4   Verified                                                      3248 non-null   object
 5   Meds Sent Down                                                318 non-null    object
 6   Checked                                                       3249 non-null   object
 7   Counselled                                                    996 non-null    object
 8   Remarks
(input paeds if it is a 4P patient in 4A)             2425 non-null   object
 9   Checked by Pharmacist                                         3243 non-null   object
 10  Time to Ready for Collection                                  3244 non-null   object
 11  Time to Counselling                                           992 non-null    object
 12  No. of Items                                                  988 non-null    object
 13  Bedside Counselling Candidate                                 2759 non-null   object
 14  Dispensed by                                                  993 non-null    object
 15  PML given?                                                    563 non-null    object
 16  If not given, WHY?! If given, were any interventions needed?  268 non-null    object
dtypes: object(17)
memory usage: 461.4+ KB

In [10]:
df2.tail()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
3442,2021-12-31 00:00:00,3B,3610,3.02105e+09,15:10:00,NaN,15:25:00,NaN,NaN,DH,00:15:00,NaN,NaN,,NaN,NaN,NaN
3443,2021-12-31 00:00:00,3B,3605,3.02105e+09,16:26:00,NaN,16:32:00,NaN,NaN,DH,00:06:00,NaN,NaN,,NaN,NaN,NaN
3447,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3448,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3449,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN

In [12]:
df2.drop(df2.tail(3).index,inplace=True)

In [11]:
#export to excel
#df2.to_excel('merged_PEH_TTO_Data.xlsx', 
#             engine='xlsxwriter', 
#             sheet_name='Merged',
#             header = True,
#             index=False)

In [16]:
#export to csv
df2.to_csv('merged_PEH_TTO_Data.csv',
            header=True,
            index=False)

In [25]:
#read csv for further cleaning
df_csv = pd.read_csv('merged_PEH_TTO_Data.csv')
df_csv.head()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
0,2021-01-04 00:00:00,4A,4811.0,3021000132.0,09:52:00,NaN,10:00:00,10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN
1,2021-01-04 00:00:00,3A,3828.0,3020041950.0,08:34:00,NaN,08:44:00,NaN,NaN,TFP,00:10:00,NaN,NaN,,NaN,NaN,NaN
2,2021-01-04 00:00:00,3B,3606.0,3021000166.0,09:15:00,09:40:00,09:50:00,09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN
3,2021-01-04 00:00:00,DAY,2011.0,3021000242.0,10:09:00,NaN,10:20:00,NaN,NaN,TFP,00:11:00,NaN,NaN,,NaN,NaN,NaN
4,2021-01-04 00:00:00,4B,4610.0,3020044361.0,08:37:00,NaN,08:47:00,NaN,PATIENT FOR HOME ON WED,YSM,00:10:00,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
#Clean Values

#All empty or NaN values to 'NA'
#df_csv = df_csv.fillna("NA", inplace=True)
#Remove Time format in Date Column
#df_csv['Date'] = pd.to_datetime(df_csv['Date']).date()

#df_csv.head()

In [33]:
df_csv.info()

AttributeError: 'NoneType' object has no attribute 'info'