# PEH Pharmacy Department

## Step 1: Import necessary packages

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

## Data Cleaning

## Step 2: Read and combine all excel tabs into one

In [3]:
#Combining all Excel sheets into one --Assuming all have the same headers

f = '../../Data/Pharmacy Dept/PEH TTO Data/PEH TTO Data.xlsx'
df = pd.read_excel(f, sheet_name=None)
df2 = pd.concat(df, ignore_index=True)

df2.head()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?",Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,2021-01-04,4A,4811,3.021e+09,09:52:00,NaN,10:00:00,10:10:00,NaN,TFP,00:08:00,00:18:00,3,Yes,TFP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-04,3A,3828,3.02004e+09,08:34:00,NaN,08:44:00,NaN,NaN,TFP,00:10:00,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,3B,3606,3.021e+09,09:15:00,09:40:00,09:50:00,09:55:00,NaN,TFP,00:10:00,00:15:00,2,Yes,TFP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-04,DAY,2011,3.021e+09,10:09:00,NaN,10:20:00,NaN,NaN,TFP,00:11:00,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-01-04,4B,4610,3.02004e+09,08:37:00,NaN,08:47:00,NaN,PATIENT FOR HOME ON WED,YSM,00:10:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Step 3: Drop unnecessary columns

In [4]:
df2.drop(df2.columns[df2.columns.str.contains('Unnamed')], axis=1, inplace=True)
df2.head()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
0,2021-01-04,4A,4811,3.021e+09,09:52:00,NaN,10:00:00,10:10:00,NaN,TFP,00:08:00,00:18:00,3,Yes,TFP,NaN,NaN
1,2021-01-04,3A,3828,3.02004e+09,08:34:00,NaN,08:44:00,NaN,NaN,TFP,00:10:00,NaN,NaN,,NaN,NaN,NaN
2,2021-01-04,3B,3606,3.021e+09,09:15:00,09:40:00,09:50:00,09:55:00,NaN,TFP,00:10:00,00:15:00,2,Yes,TFP,NaN,NaN
3,2021-01-04,DAY,2011,3.021e+09,10:09:00,NaN,10:20:00,NaN,NaN,TFP,00:11:00,NaN,NaN,,NaN,NaN,NaN
4,2021-01-04,4B,4610,3.02004e+09,08:37:00,NaN,08:47:00,NaN,PATIENT FOR HOME ON WED,YSM,00:10:00,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3450 entries, 0 to 3449
Data columns (total 17 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Date                                                          3252 non-null   datetime64[ns]
 1   Ward                                                          3238 non-null   object
 2   Room                                                          3243 non-null   object
 3   Case Number                                                   3244 non-null   object
 4   Verified                                                      3248 non-null   object
 5   Meds Sent Down                                                318 non-null    object
 6   Checked                                                       3249 non-null   object
 7   Counselled                                                    996 non-null    object
 8   Remarks
(input paeds if it is a 4P patient in 4A)             2425 non-null   object
 9   Checked by Pharmacist                                         3243 non-null   object
 10  Time to Ready for Collection                                  3244 non-null   object
 11  Time to Counselling                                           992 non-null    object
 12  No. of Items                                                  988 non-null    object
 13  Bedside Counselling Candidate                                 2759 non-null   object
 14  Dispensed by                                                  993 non-null    object
 15  PML given?                                                    563 non-null    object
 16  If not given, WHY?! If given, were any interventions needed?  268 non-null    object
dtypes: datetime64[ns](1), object(16)
memory usage: 458.3+ KB

In [6]:
df2.dropna(axis = 0, how = 'all', inplace = True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3281 entries, 0 to 3449
Data columns (total 17 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Date                                                          3252 non-null   datetime64[ns]
 1   Ward                                                          3238 non-null   object
 2   Room                                                          3243 non-null   object
 3   Case Number                                                   3244 non-null   object
 4   Verified                                                      3248 non-null   object
 5   Meds Sent Down                                                318 non-null    object
 6   Checked                                                       3249 non-null   object
 7   Counselled                                                    996 non-null    object
 8   Remarks
(input paeds if it is a 4P patient in 4A)             2425 non-null   object
 9   Checked by Pharmacist                                         3243 non-null   object
 10  Time to Ready for Collection                                  3244 non-null   object
 11  Time to Counselling                                           992 non-null    object
 12  No. of Items                                                  988 non-null    object
 13  Bedside Counselling Candidate                                 2759 non-null   object
 14  Dispensed by                                                  993 non-null    object
 15  PML given?                                                    563 non-null    object
 16  If not given, WHY?! If given, were any interventions needed?  268 non-null    object
dtypes: datetime64[ns](1), object(16)
memory usage: 461.4+ KB

In [7]:
df2.tail()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
3442,2021-12-31,3B,3610,3.02105e+09,15:10:00,NaN,15:25:00,NaN,NaN,DH,00:15:00,NaN,NaN,,NaN,NaN,NaN
3443,2021-12-31,3B,3605,3.02105e+09,16:26:00,NaN,16:32:00,NaN,NaN,DH,00:06:00,NaN,NaN,,NaN,NaN,NaN
3447,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3448,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3449,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN

In [8]:
df2.drop(df2.tail(3).index,inplace=True)

In [9]:
df2.tail()

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
3439,2021-12-31,3B,3611,3.02105e+09,09:50:00,NaN,10:08:00,10:26:00,NaN,TCE,00:18:00,00:36:00,6,Yes,TCE,NaN,NaN
3440,2021-12-31,3B,3620,3.02105e+09,11:02:00,NaN,11:05:00,11:15:00,NaN,YZJ,00:03:00,00:13:00,1,Yes,TCE,NaN,NaN
3441,2021-12-31,3A,3826,3.02105e+09,13:05:00,NaN,13:16:00,NaN,NaN,YSM,00:11:00,NaN,NaN,,NaN,NaN,NaN
3442,2021-12-31,3B,3610,3.02105e+09,15:10:00,NaN,15:25:00,NaN,NaN,DH,00:15:00,NaN,NaN,,NaN,NaN,NaN
3443,2021-12-31,3B,3605,3.02105e+09,16:26:00,NaN,16:32:00,NaN,NaN,DH,00:06:00,NaN,NaN,,NaN,NaN,NaN

## Step 4: Export to CSV from Excel

In [10]:
#export to csv
df2.to_csv('../../Data/Pharmacy Dept/Data Cleaning/PEH_TTO_Data_Merged.csv', header=True,index=False)

## Data Cleaning

## Step 5: Read merged csv file

In [11]:
#read csv for further cleaning
df_csv = pd.read_csv('../../Data/Pharmacy Dept/Data Cleaning/PEH_TTO_Data_Merged.csv')
df_csv

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
0,2021-01-04,4A,4811.0,3021000132.0,09:52:00,NaN,10:00:00,10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN
1,2021-01-04,3A,3828.0,3020041950.0,08:34:00,NaN,08:44:00,NaN,NaN,TFP,00:10:00,NaN,NaN,,NaN,NaN,NaN
2,2021-01-04,3B,3606.0,3021000166.0,09:15:00,09:40:00,09:50:00,09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN
3,2021-01-04,DAY,2011.0,3021000242.0,10:09:00,NaN,10:20:00,NaN,NaN,TFP,00:11:00,NaN,NaN,,NaN,NaN,NaN
4,2021-01-04,4B,4610.0,3020044361.0,08:37:00,NaN,08:47:00,NaN,PATIENT FOR HOME ON WED,YSM,00:10:00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3273,2021-12-31,3B,3611.0,3021047321.0,09:50:00,NaN,10:08:00,10:26:00,NaN,TCE,00:18:00,00:36:00,6.0,Yes,TCE,NaN,NaN
3274,2021-12-31,3B,3620.0,3021047584.0,11:02:00,NaN,11:05:00,11:15:00,NaN,YZJ,00:03:00,00:13:00,1.0,Yes,TCE,NaN,NaN
3275,2021-12-31,3A,3826.0,3021047432.0,13:05:00,NaN,13:16:00,NaN,NaN,YSM,00:11:00,NaN,NaN,,NaN,NaN,NaN
3276,2021-12-31,3B,3610.0,3021046836.0,15:10:00,NaN,15:25:00,NaN,NaN,DH,00:15:00,NaN,NaN,,NaN,NaN,NaN
3277,2021-12-31,3B,3605.0,3021047045.0,16:26:00,NaN,16:32:00,NaN,NaN,DH,00:06:00,NaN,NaN,,NaN,NaN,NaN

In [12]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3278 entries, 0 to 3277
Data columns (total 17 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Date                                                          3252 non-null   object
 1   Ward                                                          3238 non-null   object
 2   Room                                                          3243 non-null   object
 3   Case Number                                                   3244 non-null   object
 4   Verified                                                      3248 non-null   object
 5   Meds Sent Down                                                318 non-null    object
 6   Checked                                                       3249 non-null   object
 7   Counselled                                                    996 non-null    object
 8   Remarks
(input paeds if it is a 4P patient in 4A)             2425 non-null   object
 9   Checked by Pharmacist                                         3243 non-null   object
 10  Time to Ready for Collection                                  3244 non-null   object
 11  Time to Counselling                                           992 non-null    object
 12  No. of Items                                                  988 non-null    object
 13  Bedside Counselling Candidate                                 2756 non-null   object
 14  Dispensed by                                                  993 non-null    object
 15  PML given?                                                    563 non-null    object
 16  If not given, WHY?! If given, were any interventions needed?  268 non-null    object
dtypes: object(17)
memory usage: 435.5+ KB

## Step 6: Handle Missing Values

In [13]:
df_csv.notnull().sum()

Date                                                            3252
Ward                                                            3238
Room                                                            3243
Case Number                                                     3244
Verified                                                        3248
Meds Sent Down                                                   318
Checked                                                         3249
Counselled                                                       996
Remarks\n(input paeds if it is a 4P patient in 4A)              2425
Checked by Pharmacist                                           3243
Time to Ready for Collection                                    3244
Time to Counselling                                              992
No. of Items                                                     988
Bedside Counselling Candidate                                   2756
Dispensed by                                                     993
PML given?                                                       563
If not given, WHY?! If given, were any interventions needed?     268
dtype: int64

In [14]:
df_csv.isnull().sum()

Date                                                              26
Ward                                                              40
Room                                                              35
Case Number                                                       34
Verified                                                          30
Meds Sent Down                                                  2960
Checked                                                           29
Counselled                                                      2282
Remarks\n(input paeds if it is a 4P patient in 4A)               853
Checked by Pharmacist                                             35
Time to Ready for Collection                                      34
Time to Counselling                                             2286
No. of Items                                                    2290
Bedside Counselling Candidate                                    522
Dispensed by                                                    2285
PML given?                                                      2715
If not given, WHY?! If given, were any interventions needed?    3010
dtype: int64

### Empty Case Number

In [15]:
#What do 'Empty' Case Number means even if the system tracked a medication dispensed record?

df_csv[df_csv['Case Number'].isnull()]

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SEND UP TTO AT 1200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,2021-01-19,3A,3816.0,NaN,10:34:00,NaN,10:52:00,NaN,NaN,YSM,00:18:00,NaN,NaN,,NaN,NaN,NaN
270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
1252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Please help fill in PML Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Please help fill in PML Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TTO sent up at 1240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
1391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
1392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
1649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
1650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
1651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
1880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
1881,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
1882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
2022,2021-08-19,DAY,2002.0,NaN,12:25:00,NaN,12:38:00,NaN,,DH,00:13:00,NaN,NaN,,NaN,NaN,NaN
2024,2021-08-19,NaN,NaN,NaN,15:00:00,NaN,15:07:00,NaN,,CHAR,00:07:00,NaN,NaN,,NaN,NaN,NaN
2025,2021-08-20,NaN,NaN,NaN,00:00:00,NaN,09:22:00,09:40:00,,TCE,NaN,NaN,5.0,,DH,YES,NaN
2026,2021-08-20,NaN,NaN,NaN,11:05:00,NaN,11:13:00,11:20:00,,LLY,00:08:00,00:15:00,3.0,,DH,NaN,NaN
2027,2021-08-20,NaN,NaN,NaN,10:30:00,NaN,10:38:00,10:55:00,,DH,00:08:00,00:25:00,5.0,,DH,NaN,NaN
2028,2021-08-20,NaN,NaN,NaN,09:25:00,NaN,09:33:00,09:41:00,,DH,00:08:00,00:16:00,NaN,,DH,NO,<24HR
2128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
2129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
2130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
2712,2021-10-27,3B,3609,NaN,08:30:00,NaN,08:48:00,NaN,,YSM,00:18:00,NaN,NaN,NaN,NaN,NaN,NaN
3008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
3010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN

In [16]:
df_csv = df_csv.dropna(subset=['Date'])

df_csv.isnull().sum()

Date                                                               0
Ward                                                              14
Room                                                               9
Case Number                                                        8
Verified                                                           4
Meds Sent Down                                                  2934
Checked                                                            3
Counselled                                                      2256
Remarks\n(input paeds if it is a 4P patient in 4A)               832
Checked by Pharmacist                                              9
Time to Ready for Collection                                       8
Time to Counselling                                             2260
No. of Items                                                    2264
Bedside Counselling Candidate                                    518
Dispensed by                                                    2259
PML given?                                                      2689
If not given, WHY?! If given, were any interventions needed?    2984
dtype: int64

In [17]:
df_csv[df_csv['Case Number'].isnull()]

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
142,2021-01-19,3A,3816.0,NaN,10:34:00,NaN,10:52:00,NaN,NaN,YSM,00:18:00,NaN,NaN,,NaN,NaN,NaN
2022,2021-08-19,DAY,2002.0,NaN,12:25:00,NaN,12:38:00,NaN,,DH,00:13:00,NaN,NaN,,NaN,NaN,NaN
2024,2021-08-19,NaN,NaN,NaN,15:00:00,NaN,15:07:00,NaN,,CHAR,00:07:00,NaN,NaN,,NaN,NaN,NaN
2025,2021-08-20,NaN,NaN,NaN,00:00:00,NaN,09:22:00,09:40:00,,TCE,NaN,NaN,5.0,,DH,YES,NaN
2026,2021-08-20,NaN,NaN,NaN,11:05:00,NaN,11:13:00,11:20:00,,LLY,00:08:00,00:15:00,3.0,,DH,NaN,NaN
2027,2021-08-20,NaN,NaN,NaN,10:30:00,NaN,10:38:00,10:55:00,,DH,00:08:00,00:25:00,5.0,,DH,NaN,NaN
2028,2021-08-20,NaN,NaN,NaN,09:25:00,NaN,09:33:00,09:41:00,,DH,00:08:00,00:16:00,NaN,,DH,NO,<24HR
2712,2021-10-27,3B,3609,NaN,08:30:00,NaN,08:48:00,NaN,,YSM,00:18:00,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
#Affix "EMPTY" if Case Number = NaN
df_csv.loc[df_csv['Case Number'].isnull(), 'Case Number'] = "EMPTY"

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
<ipython-input-18-245c6709ddb1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv.loc[df_csv['Case Number'].isnull(), 'Case Number'] = "EMPTY"

In [19]:
df_csv[df_csv['Case Number'] == "EMPTY"]

,Date,Ward,Room,Case Number,Verified,Meds Sent Down,Checked,Counselled,Remarks\n(input paeds if it is a 4P patient in 4A),Checked by Pharmacist,Time to Ready for Collection,Time to Counselling,No. of Items,Bedside Counselling Candidate,Dispensed by,PML given?,"If not given, WHY?! If given, were any interventions needed?"
142,2021-01-19,3A,3816.0,EMPTY,10:34:00,NaN,10:52:00,NaN,NaN,YSM,00:18:00,NaN,NaN,,NaN,NaN,NaN
2022,2021-08-19,DAY,2002.0,EMPTY,12:25:00,NaN,12:38:00,NaN,,DH,00:13:00,NaN,NaN,,NaN,NaN,NaN
2024,2021-08-19,NaN,NaN,EMPTY,15:00:00,NaN,15:07:00,NaN,,CHAR,00:07:00,NaN,NaN,,NaN,NaN,NaN
2025,2021-08-20,NaN,NaN,EMPTY,00:00:00,NaN,09:22:00,09:40:00,,TCE,NaN,NaN,5.0,,DH,YES,NaN
2026,2021-08-20,NaN,NaN,EMPTY,11:05:00,NaN,11:13:00,11:20:00,,LLY,00:08:00,00:15:00,3.0,,DH,NaN,NaN
2027,2021-08-20,NaN,NaN,EMPTY,10:30:00,NaN,10:38:00,10:55:00,,DH,00:08:00,00:25:00,5.0,,DH,NaN,NaN
2028,2021-08-20,NaN,NaN,EMPTY,09:25:00,NaN,09:33:00,09:41:00,,DH,00:08:00,00:16:00,NaN,,DH,NO,<24HR
2712,2021-10-27,3B,3609,EMPTY,08:30:00,NaN,08:48:00,NaN,,YSM,00:18:00,NaN,NaN,NaN,NaN,NaN,NaN

## Step 7: Rename Columns

In [20]:
#Rename Columns for future standardization
new_cols_name = {'Room': 'Room/Bed',
                'Verified': 'DateTime TTO Received', 
                'Meds Sent Down': 'DateTime (Meds Sent Down)', 
                'Checked': 'DateTime TTO Checked', 
                'Counselled': 'DateTime (Counselled)', 
                'Remarks\n(input paeds if it is a 4P patient in 4A)': 'Remarks', 
                'Checked by Pharmacist': 'Checked By (Pharmacist)', 
                'Time to Ready for Collection': 'Time Taken (Ready for Collection)', 
                'Time to Counselling': 'Time Taken (to Counselling)', 
                'No. of Items': 'No. of Drugs',
                'PML given?': 'PML',
                'If not given, WHY?! If given, were any interventions needed?': 'No PML Remarks'}

df_csv.rename(columns=new_cols_name, inplace=True)

df_csv.head()

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks
0,2021-01-04,4A,4811.0,3021000132.0,09:52:00,NaN,10:00:00,10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN
1,2021-01-04,3A,3828.0,3020041950.0,08:34:00,NaN,08:44:00,NaN,NaN,TFP,00:10:00,NaN,NaN,,NaN,NaN,NaN
2,2021-01-04,3B,3606.0,3021000166.0,09:15:00,09:40:00,09:50:00,09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN
3,2021-01-04,DAY,2011.0,3021000242.0,10:09:00,NaN,10:20:00,NaN,NaN,TFP,00:11:00,NaN,NaN,,NaN,NaN,NaN
4,2021-01-04,4B,4610.0,3020044361.0,08:37:00,NaN,08:47:00,NaN,PATIENT FOR HOME ON WED,YSM,00:10:00,NaN,NaN,NaN,NaN,NaN,NaN

## Step 8: Fix Data Type(s) for Time

In [21]:
#Add Date to Time Only Columns
df_csv.loc[:,'DateTime TTO Received'] = pd.to_datetime((df_csv['Date'].astype(str) + ' ' + df_csv['DateTime TTO Received'].astype(str)), infer_datetime_format=True, errors='coerce')
df_csv.loc[:,'DateTime (Meds Sent Down)'] = pd.to_datetime((df_csv['Date'].astype(str) + ' ' + df_csv['DateTime (Meds Sent Down)'].astype(str)), infer_datetime_format=True, errors='coerce')
df_csv.loc[:,'DateTime TTO Checked'] = pd.to_datetime((df_csv['Date'].astype(str) + ' ' + df_csv['DateTime TTO Checked'].astype(str)), infer_datetime_format=True, errors='coerce')
df_csv.loc[:,'DateTime (Counselled)'] = pd.to_datetime((df_csv['Date'].astype(str) + ' ' + df_csv['DateTime (Counselled)'].astype(str)), infer_datetime_format=True, errors='coerce')

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1048: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [22]:
#Change 'Date' Column to datetime
df_csv['Date'] = pd.to_datetime(df_csv['Date'], infer_datetime_format=True, errors='coerce')

<ipython-input-22-faa764c8f5fb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Date'] = pd.to_datetime(df_csv['Date'], infer_datetime_format=True, errors='coerce')

In [23]:
#Change 'Date' Column to datetime.dt.date
df_csv['Date'] = df_csv['Date'].dt.date

<ipython-input-23-0e72d1b2ae2b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Date'] = df_csv['Date'].dt.date

In [24]:
#FIXED with latest dataset

#Drop invalid Time (Case Number: 3021022234, 3021022185, 3021026234, 3021032879, 3021032837, 3021000560)
#Drop invalid Date (Date: 'dfdfdf', Case Number: 3021031272)
#Dropped externally as format do not fit

In [25]:
#Change 'Time TTO Received', 'Time (Meds Sent Down)', 'Time TTO Checked', 'Time (Counselled)'
#       'Time Taken (Ready for Collection)', 'Time Taken (to Counselling)' 
#       Columns to datetime.dt.time

#df_csv['Time TTO Received'] = pd.to_datetime(df_csv['DateTime TTO Received'], format='%H:%M:%S').dt.time
#df_csv['Time (Meds Sent Down)'] = pd.to_datetime(df_csv['DateTime (Meds Sent Down)'], format='%H:%M:%S').dt.time
#df_csv['Time TTO Checked'] = pd.to_datetime(df_csv['DateTime TTO Checked'], format='%H:%M:%S').dt.time
#df_csv['Time (Counselled)'] = pd.to_datetime(df_csv['DateTime (Counselled)'], format='%H:%M:%S').dt.time
df_csv['Time Taken (Ready for Collection)'] = pd.to_datetime(df_csv['Time Taken (Ready for Collection)'], format='%H:%M:%S').dt.time
df_csv['Time Taken (to Counselling)'] = pd.to_datetime(df_csv['Time Taken (to Counselling)'], format='%H:%M:%S').dt.time

<ipython-input-25-2b406034c904>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Time Taken (Ready for Collection)'] = pd.to_datetime(df_csv['Time Taken (Ready for Collection)'], format='%H:%M:%S').dt.time
<ipython-input-25-2b406034c904>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Time Taken (to Counselling)'] = pd.to_datetime(df_csv['Time Taken (to Counselling)'], format='%H:%M:%S').dt.time

In [26]:
#Change 'NaT/NaN' to '00:00:00'

#df_csv['Time TTO Received'] = df_csv['Time TTO Received'].fillna(pd.Timedelta(seconds=0))
#df_csv['Time (Meds Sent Down)'] = df_csv['Time (Meds Sent Down)'].fillna(pd.Timedelta(seconds=0))
#df_csv['Time TTO Checked'] = df_csv['Time TTO Checked'].fillna(pd.Timedelta(seconds=0))
#df_csv['Time (Counselled)'] = df_csv['Time (Counselled)'].fillna(pd.Timedelta(seconds=0))
#df_csv['Time Taken (Ready for Collection)'] = df_csv['Time Taken (Ready for Collection)'].fillna(pd.Timedelta(seconds=0))
#df_csv['Time Taken (to Counselling)'] = df_csv['Time Taken (to Counselling)'].fillna(pd.Timedelta(seconds=0))

In [27]:
#Remove '0 days' in all Time data type

#df_csv['Time TTO Received'] = df_csv['Time TTO Received'].astype(str).str.split('0 days ').str[-1]
#df_csv['Time (Meds Sent Down)'] = df_csv['Time (Meds Sent Down)'].astype(str).str.split('0 days ').str[-1]
#df_csv['Time TTO Checked'] = df_csv['Time TTO Checked'].astype(str).str.split('0 days ').str[-1]
#df_csv['Time (Counselled)'] = df_csv['Time (Counselled)'].astype(str).str.split('0 days ').str[-1]
#df_csv['Time Taken (Ready for Collection)'] = df_csv['Time Taken (Ready for Collection)'].astype(str).str.split('0 days ').str[-1]
#df_csv['Time Taken (to Counselling)'] = df_csv['Time Taken (to Counselling)'].astype(str).str.split('0 days ').str[-1]

In [28]:
#reinstate into Time format again

#df_csv['Time TTO Received'] = pd.to_datetime(df_csv['Time TTO Received'], format='%H:%M:%S').dt.time
#df_csv['Time (Meds Sent Down)'] = pd.to_datetime(df_csv['Time (Meds Sent Down)'], format='%H:%M:%S').dt.time
#df_csv['Time TTO Checked'] = pd.to_datetime(df_csv['Time TTO Checked'], format='%H:%M:%S').dt.time
#df_csv['Time (Counselled)'] = pd.to_datetime(df_csv['Time (Counselled)'], format='%H:%M:%S').dt.time
#df_csv['Time Taken (Ready for Collection)'] = pd.to_datetime(df_csv['Time Taken (Ready for Collection)'], format='%H:%M:%S').dt.time
#df_csv['Time Taken (to Counselling)'] = pd.to_datetime(df_csv['Time Taken (to Counselling)'], format='%H:%M:%S').dt.time

In [29]:
df_csv.head()

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks
0,2021-01-04,4A,4811.0,3021000132.0,2021-01-04 09:52:00,NaT,2021-01-04 10:00:00,2021-01-04 10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN
1,2021-01-04,3A,3828.0,3020041950.0,2021-01-04 08:34:00,NaT,2021-01-04 08:44:00,NaT,NaN,TFP,00:10:00,NaT,NaN,,NaN,NaN,NaN
2,2021-01-04,3B,3606.0,3021000166.0,2021-01-04 09:15:00,2021-01-04 09:40:00,2021-01-04 09:50:00,2021-01-04 09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN
3,2021-01-04,DAY,2011.0,3021000242.0,2021-01-04 10:09:00,NaT,2021-01-04 10:20:00,NaT,NaN,TFP,00:11:00,NaT,NaN,,NaN,NaN,NaN
4,2021-01-04,4B,4610.0,3020044361.0,2021-01-04 08:37:00,NaT,2021-01-04 08:47:00,NaT,PATIENT FOR HOME ON WED,YSM,00:10:00,NaT,NaN,NaN,NaN,NaN,NaN

## Step 9: Fix NaN values in non-Time Data Type

In [30]:
#No. of Drugs 
#df_csv['No. of Drugs'] = df_csv['No. of Drugs'].fillna("NA")

In [31]:
#Bedside Counselling Candidate
df_csv['Bedside Counselling Candidate'] = df_csv['Bedside Counselling Candidate'].fillna('No')

#IF Time Taken (to Counselling) == 00:00:00 or np.NaN, then Bedside Counselling Candidate = No
df_csv.loc[((df_csv['Time Taken (to Counselling)'] == pd.to_datetime('00:00:00').time()) | (df_csv['Time Taken (to Counselling)'].isna())), 'Bedside Counselling Candidate'] = "No"

#IF Time (to Counselling) > 00:00:00, then Bedside Counselling Candidate = Yes
df_csv.loc[(df_csv['Time Taken (to Counselling)'] > pd.to_datetime('00:00:00').time()), 'Bedside Counselling Candidate'] = "Yes"

<ipython-input-31-877237293de4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Bedside Counselling Candidate'] = df_csv['Bedside Counselling Candidate'].fillna('No')
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [32]:
df_csv.isnull().sum()

Date                                    0
Ward                                   14
Room/Bed                                9
Case Number                             0
DateTime TTO Received                   4
DateTime (Meds Sent Down)            2934
DateTime TTO Checked                    3
DateTime (Counselled)                2256
Remarks                               832
Checked By (Pharmacist)                 9
Time Taken (Ready for Collection)       8
Time Taken (to Counselling)          2260
No. of Drugs                         2264
Bedside Counselling Candidate           0
Dispensed by                         2259
PML                                  2689
No PML Remarks                       2984
dtype: int64

In [34]:
dfinal = df_csv

## EDA

## Step 10: Get Day of Week

In [35]:
dfinal['Weekday'] = pd.to_datetime(dfinal['Date']).dt.day_name()

#Fill NaN with empty string for those without a Date
#dfinal['Weekday'] = dfinal['Weekday'].fillna('')

dfinal.head()

<ipython-input-35-c7f09d5c1f1a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Weekday'] = pd.to_datetime(dfinal['Date']).dt.day_name()

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday
0,2021-01-04,4A,4811.0,3021000132.0,2021-01-04 09:52:00,NaT,2021-01-04 10:00:00,2021-01-04 10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN,Monday
1,2021-01-04,3A,3828.0,3020041950.0,2021-01-04 08:34:00,NaT,2021-01-04 08:44:00,NaT,NaN,TFP,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday
2,2021-01-04,3B,3606.0,3021000166.0,2021-01-04 09:15:00,2021-01-04 09:40:00,2021-01-04 09:50:00,2021-01-04 09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN,Monday
3,2021-01-04,DAY,2011.0,3021000242.0,2021-01-04 10:09:00,NaT,2021-01-04 10:20:00,NaT,NaN,TFP,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Monday
4,2021-01-04,4B,4610.0,3020044361.0,2021-01-04 08:37:00,NaT,2021-01-04 08:47:00,NaT,PATIENT FOR HOME ON WED,YSM,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday

## Step 11: Calculate Time TTO Dispensed 

PEH does not have a Time TTO Dispensed indicator in their original raw dataset

In [36]:
#IF time counselled > time checked : time dispensed == time counselled
#else time dispensed == time checked

dfinal['DateTime TTO Dispensed'] = np.where((dfinal['DateTime (Counselled)'] > dfinal['DateTime TTO Checked']), 
                                        dfinal['DateTime (Counselled)'], dfinal['DateTime TTO Checked'])

dfinal.head()

<ipython-input-36-5d91989f4921>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['DateTime TTO Dispensed'] = np.where((dfinal['DateTime (Counselled)'] > dfinal['DateTime TTO Checked']),

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed
0,2021-01-04,4A,4811.0,3021000132.0,2021-01-04 09:52:00,NaT,2021-01-04 10:00:00,2021-01-04 10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 10:10:00
1,2021-01-04,3A,3828.0,3020041950.0,2021-01-04 08:34:00,NaT,2021-01-04 08:44:00,NaT,NaN,TFP,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:44:00
2,2021-01-04,3B,3606.0,3021000166.0,2021-01-04 09:15:00,2021-01-04 09:40:00,2021-01-04 09:50:00,2021-01-04 09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 09:55:00
3,2021-01-04,DAY,2011.0,3021000242.0,2021-01-04 10:09:00,NaT,2021-01-04 10:20:00,NaT,NaN,TFP,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 10:20:00
4,2021-01-04,4B,4610.0,3020044361.0,2021-01-04 08:37:00,NaT,2021-01-04 08:47:00,NaT,PATIENT FOR HOME ON WED,YSM,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:47:00

## Step 12: Get Overall Time Taken (TAT)

In [37]:
dfinal['TAT'] = np.where(
                            (dfinal['Time Taken (to Counselling)'].isnull()), 
                            pd.to_datetime(dfinal['Time Taken (Ready for Collection)'].astype(str)).dt.minute, 
                            pd.to_datetime(dfinal['Time Taken (to Counselling)'].astype(str)).dt.minute)

dfinal.head()

<ipython-input-37-011cd524a800>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['TAT'] = np.where(

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed,TAT
0,2021-01-04,4A,4811.0,3021000132.0,2021-01-04 09:52:00,NaT,2021-01-04 10:00:00,2021-01-04 10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 10:10:00,18.0
1,2021-01-04,3A,3828.0,3020041950.0,2021-01-04 08:34:00,NaT,2021-01-04 08:44:00,NaT,NaN,TFP,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:44:00,10.0
2,2021-01-04,3B,3606.0,3021000166.0,2021-01-04 09:15:00,2021-01-04 09:40:00,2021-01-04 09:50:00,2021-01-04 09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 09:55:00,15.0
3,2021-01-04,DAY,2011.0,3021000242.0,2021-01-04 10:09:00,NaT,2021-01-04 10:20:00,NaT,NaN,TFP,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 10:20:00,11.0
4,2021-01-04,4B,4610.0,3020044361.0,2021-01-04 08:37:00,NaT,2021-01-04 08:47:00,NaT,PATIENT FOR HOME ON WED,YSM,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:47:00,10.0

In [38]:
#pd.set_option('display.max_columns', None)
dfinal[dfinal['TAT'].isnull()]

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed,TAT
405,2021-02-17,3A,3821.0,3021005452.0,NaT,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaN,No,NaN,NaN,NaN,Wednesday,NaT,NaN
1223,2021-05-10,3A,3824.0,3021014976.0,2021-05-10 09:30:00,NaT,2021-05-10 08:35:00,NaT,NaN,AT,NaT,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-05-10 08:35:00,NaN
1430,2021-06-04,4B,4609.0,3021018969.0,NaT,NaT,NaT,NaT,Verified on 3/6. Pt in physio passed to SN,AT,NaT,NaT,NaN,No,NaN,NaN,NaN,Friday,NaT,NaN
2023,2021-08-19,NaN,NaN,dd,2021-08-19 00:00:00,NaT,2021-08-19 14:08:00,NaT,,CHAR,NaT,NaT,NaN,No,NaN,NaN,NaN,Thursday,2021-08-19 14:08:00,NaN
2025,2021-08-20,NaN,NaN,EMPTY,2021-08-20 00:00:00,NaT,2021-08-20 09:22:00,2021-08-20 09:40:00,,TCE,NaT,NaT,5.0,No,DH,YES,NaN,Friday,2021-08-20 09:40:00,NaN
2029,2021-08-20,4B,4610.0,3021028838,2021-08-20 00:00:00,NaT,2021-08-20 11:36:00,NaT,SN DISPENSE,LLY,NaT,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-08-20 11:36:00,NaN

In [39]:
#Time TTO Dispensed - Time (Counselled) - Time TTO Checked - Time (Meds Sent Down) - Time TTO Received

#IF Time (Counselled) != 00:00:00 & IF Time (Meds Sent Down) != 00:00:00, Subtract all from Time TTO Dispensed
#IF Time (Counselled) == 00:00:00 & Time (Meds Sent Down) == 00:00:00, Time TTO Dispensed - Time TTO Checked - Time TTO Received
#IF Time (Counselled) == 00:00:00 & Time (Meds Sent Down) != 00:00:00, Time TTO Dispensed - Time TTO Checked - Time (Meds Sent Down) - Time TTO Received
#IF Time (Counselled) != 00:00:00 & Time (Meds Sent Down) == 00:00:00, Time TTO Dispensed - Time (Counselled) - Time TTO Checked - Time TTO Received

#df_test = dfinal
#
#df_test['Overall Time Taken to Dispensed'] = np.where(  
#                                                    (df_test['Time (Counselled)'] != pd.to_datetime('00:00:00').time()) & 
#                                                    (df_test['Time (Meds Sent Down)'] != pd.to_datetime('00:00:00').time()),
#                                                        (pd.to_timedelta(df_test['Time TTO Dispensed'].astype(str)) 
#                                                        - pd.to_timedelta(df_test['Time (Counselled)'].astype(str)) 
#                                                        - pd.to_timedelta(df_test['Time TTO Checked'].astype(str)) 
#                                                        - pd.to_timedelta(df_test['Time (Meds Sent Down)'].astype(str)) 
#                                                        - pd.to_timedelta(df_test['Time TTO Received'].astype(str))) ,
#                                                        
#                                                    np.where(
#                                                        (df_test['Time (Counselled)'] == pd.to_datetime('00:00:00').time()) & 
#                                                        (df_test['Time (Meds Sent Down)'] == pd.to_datetime('00:00:00').time()),
#                                                            (pd.to_timedelta(df_test['Time TTO Dispensed'].astype(str))                                     
#                                                            - pd.to_timedelta(df_test['Time TTO Checked'].astype(str))                                                            
#                                                            - pd.to_timedelta(df_test['Time TTO Received'].astype(str))) ,
#
#                                                    np.where(
#                                                        (df_test['Time (Counselled)'] == pd.to_datetime('00:00:00').time()) & 
#                                                        (df_test['Time (Meds Sent Down)'] != pd.to_datetime('00:00:00').time()),
#                                                            (pd.to_timedelta(df_test['Time TTO Dispensed'].astype(str))                                                             
#                                                            - pd.to_timedelta(df_test['Time TTO Checked'].astype(str)) 
#                                                            - pd.to_timedelta(df_test['Time (Meds Sent Down)'].astype(str)) 
#                                                            - pd.to_timedelta(df_test['Time TTO Received'].astype(str))) ,
#
#                                                    np.where(
#                                                        (df_test['Time (Counselled)'] != pd.to_datetime('00:00:00').time()) & 
#                                                        (df_test['Time (Meds Sent Down)'] == pd.to_datetime('00:00:00').time()),
#                                                            (pd.to_timedelta(df_test['Time TTO Dispensed'].astype(str)) 
#                                                            - pd.to_timedelta(df_test['Time (Counselled)'].astype(str)) 
#                                                            - pd.to_timedelta(df_test['Time TTO Checked'].astype(str))                                                             
#                                                            - pd.to_timedelta(df_test['Time TTO Received'].astype(str))) , 
#
#                                                            np.NaN))))
#
#                                                            
#df_test

#dfinal['Overall Time Taken to Dispensed'] = (pd.to_timedelta(dfinal['Time TTO Dispensed'].astype(str)) 
#                                            - pd.to_timedelta(dfinal['Time (Counselled)'].astype(str)) 
#                                            - pd.to_timedelta(dfinal['Time TTO Checked'].astype(str)) 
#                                            - pd.to_timedelta(dfinal['Time (Meds Sent Down)'].astype(str)) 
#                                            - pd.to_timedelta(dfinal['Time TTO Received'].astype(str)))

In [40]:
#def td_to_hmsstr(td):
#    """
#    convert a timedelta object td to a string in HH:MM:SS format.
#    """
#    hours, remainder = divmod(td.total_seconds(), 3600)
#    minutes, seconds = divmod(remainder, 60)
#    return f'{int(hours):02}:{int(minutes):02}:{int(seconds):02}'
#
#
#df_test['Overall Time Taken to Dispensed'] = df_test['Overall Time Taken to Dispensed'].apply(td_to_hmsstr)
#df_test

## Step 13: Create Meet KPI column with yes/no value

GEH: Total Time Taken < 45mins = Yes, else: No.

In [41]:
dfinal['Meet KPI'] = np.where((dfinal['TAT'].isnull()), "NA",
                            np.where((dfinal['TAT'] <= (pd.to_datetime('00:45:00')).minute),
                                    'Yes', 'No'))

dfinal

<ipython-input-41-bea018ab2f9c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Meet KPI'] = np.where((dfinal['TAT'].isnull()), "NA",

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed,TAT,Meet KPI
0,2021-01-04,4A,4811.0,3021000132.0,2021-01-04 09:52:00,NaT,2021-01-04 10:00:00,2021-01-04 10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 10:10:00,18.0,Yes
1,2021-01-04,3A,3828.0,3020041950.0,2021-01-04 08:34:00,NaT,2021-01-04 08:44:00,NaT,NaN,TFP,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:44:00,10.0,Yes
2,2021-01-04,3B,3606.0,3021000166.0,2021-01-04 09:15:00,2021-01-04 09:40:00,2021-01-04 09:50:00,2021-01-04 09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 09:55:00,15.0,Yes
3,2021-01-04,DAY,2011.0,3021000242.0,2021-01-04 10:09:00,NaT,2021-01-04 10:20:00,NaT,NaN,TFP,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 10:20:00,11.0,Yes
4,2021-01-04,4B,4610.0,3020044361.0,2021-01-04 08:37:00,NaT,2021-01-04 08:47:00,NaT,PATIENT FOR HOME ON WED,YSM,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:47:00,10.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3273,2021-12-31,3B,3611.0,3021047321.0,2021-12-31 09:50:00,NaT,2021-12-31 10:08:00,2021-12-31 10:26:00,NaN,TCE,00:18:00,00:36:00,6.0,Yes,TCE,NaN,NaN,Friday,2021-12-31 10:26:00,36.0,Yes
3274,2021-12-31,3B,3620.0,3021047584.0,2021-12-31 11:02:00,NaT,2021-12-31 11:05:00,2021-12-31 11:15:00,NaN,YZJ,00:03:00,00:13:00,1.0,Yes,TCE,NaN,NaN,Friday,2021-12-31 11:15:00,13.0,Yes
3275,2021-12-31,3A,3826.0,3021047432.0,2021-12-31 13:05:00,NaT,2021-12-31 13:16:00,NaT,NaN,YSM,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 13:16:00,11.0,Yes
3276,2021-12-31,3B,3610.0,3021046836.0,2021-12-31 15:10:00,NaT,2021-12-31 15:25:00,NaT,NaN,DH,00:15:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 15:25:00,15.0,Yes
3277,2021-12-31,3B,3605.0,3021047045.0,2021-12-31 16:26:00,NaT,2021-12-31 16:32:00,NaT,NaN,DH,00:06:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 16:32:00,6.0,Yes

In [42]:
dfinal[dfinal['Meet KPI']=="No"]

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed,TAT,Meet KPI
200,2021-01-25,4B,4612.0,3021002435.0,2021-01-25 08:53:00,NaT,2021-01-25 08:55:00,2021-01-25 10:50:00,NaN,DH,00:02:00,01:57:00,6.0,Yes,DH,NaN,NaN,Monday,2021-01-25 10:50:00,57.0,No
212,2021-01-26,3B,3609.0,3021002242.0,2021-01-26 09:25:00,2021-01-26 09:36:00,2021-01-26 09:55:00,2021-01-26 10:35:00,NaN,YSM,00:19:00,00:59:00,4.0,Yes,CHAR,NaN,NaN,Tuesday,2021-01-26 10:35:00,59.0,No
213,2021-01-26,3B,3610.0,3021002640.0,2021-01-26 09:00:00,2021-01-26 09:36:00,2021-01-26 10:00:00,2021-01-26 10:35:00,NaN,YSM,00:24:00,00:59:00,1.0,Yes,CHAR,NaN,NaN,Tuesday,2021-01-26 10:35:00,59.0,No
484,2021-02-25,3B,3606.0,3021006433.0,2021-02-25 09:13:00,2021-02-25 09:30:00,2021-02-25 09:58:00,2021-02-25 10:16:00,NaN,CHAR,00:28:00,00:46:00,7.0,Yes,CHAR,NaN,NaN,Thursday,2021-02-25 10:16:00,46.0,No
567,2021-03-05,3B,3606,3021006885.0,2021-03-05 09:30:00,2021-03-05 09:42:00,2021-03-05 10:25:00,2021-03-05 10:30:00,,TFP,00:43:00,00:48:00,6,Yes,TFP,NaN,NaN,Friday,2021-03-05 10:30:00,48.0,No
773,2021-03-25,4B,4605,3021010026.0,2021-03-25 09:44:00,NaT,2021-03-25 10:08:00,2021-03-25 10:40:00,Please help fill in PML Data,YSM,00:24:00,00:56:00,3,Yes,LLY,Yes,NaN,Thursday,2021-03-25 10:40:00,56.0,No
1225,2021-05-10,DAY,2011.0,3021016241.0,2021-05-10 11:31:00,NaT,2021-05-10 12:23:00,NaT,,YSL,00:52:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-05-10 12:23:00,52.0,No
1309,2021-05-19,4B,4619.0,3021017254.0,2021-05-19 10:00:00,NaT,2021-05-19 10:50:00,NaT,passed to SN,DH,00:50:00,NaT,NaN,No,NaN,NaN,NaN,Wednesday,2021-05-19 10:50:00,50.0,No
1332,2021-05-20,3A,3841.0,3021017176.0,2021-05-20 20:35:00,NaT,2021-05-20 21:26:00,NaT,Checked by duty manager,ANC SITI,00:51:00,NaT,NaN,No,NaN,NaN,NaN,Thursday,2021-05-20 21:26:00,51.0,No
1335,2021-05-21,4A,4806.0,3021017474.0,2021-05-21 08:45:00,NaT,2021-05-21 08:54:00,2021-05-21 09:37:00,,DH,00:09:00,00:52:00,3.0,Yes,DH,NaN,NaN,Friday,2021-05-21 09:37:00,52.0,No
1463,2021-06-09,4A,4803.0,3021019527.0,2021-06-09 08:05:00,NaT,2021-06-09 08:35:00,2021-06-09 08:52:00,,TCE,00:30:00,00:47:00,1.0,Yes,YZJ,NaN,NaN,Wednesday,2021-06-09 08:52:00,47.0,No
1493,2021-06-14,3B,3609.0,3021019988.0,2021-06-14 09:20:00,NaT,2021-06-14 09:55:00,2021-06-14 10:10:00,,AT,00:35:00,00:50:00,6.0,Yes,AT,NaN,NaN,Monday,2021-06-14 10:10:00,50.0,No
1606,2021-06-25,4A,4808.0,3021021292.0,2021-06-25 08:30:00,NaT,2021-06-25 08:51:00,2021-06-25 09:20:00,,YSM,00:21:00,00:50:00,3.0,Yes,YZJ,NaN,NaN,Friday,2021-06-25 09:20:00,50.0,No
1670,2021-07-02,4B,4607.0,3021022392.0,2021-07-02 07:58:00,NaT,2021-07-02 08:18:00,2021-07-02 08:50:00,Please help fill in PML Data,YSM,00:20:00,00:52:00,6.0,Yes,TFP,Yes,NaN,Friday,2021-07-02 08:50:00,52.0,No
1782,2021-07-21,3A,3817.0,3021024708.0,2021-07-21 07:10:00,NaT,2021-07-21 08:09:00,NaT,,CHAR,00:59:00,NaT,NaN,No,NaN,NaN,NaN,Wednesday,2021-07-21 08:09:00,59.0,No
1843,2021-07-28,4B,4610.0,3021025568.0,2021-07-28 07:49:00,2021-07-28 07:55:00,2021-07-28 08:14:00,2021-07-28 08:45:00,Please help fill in PML Data,YSM,00:19:00,00:50:00,3.0,Yes,YZJ,YES,NaN,Wednesday,2021-07-28 08:45:00,50.0,No
1865,2021-07-29,4B,4603.0,3021025398.0,2021-07-29 07:54:00,NaT,2021-07-29 08:10:00,2021-07-29 08:45:00,Please help fill in PML Data,TFP,00:16:00,00:51:00,5.0,Yes,TFP,Yes,NaN,Thursday,2021-07-29 08:45:00,51.0,No
2060,2021-08-24,3B,3605.0,3021029626,2021-08-24 10:44:00,NaT,2021-08-24 11:22:00,2021-08-24 11:35:00,,LLY,00:38:00,00:51:00,4.0,Yes,LLY,NaN,NaN,Tuesday,2021-08-24 11:35:00,51.0,No
2079,2021-08-26,4B,4603.0,3021029580,2021-08-26 09:09:00,NaT,2021-08-26 09:34:00,2021-08-26 09:59:00,Please help fill in PML Data,TFP,00:25:00,00:50:00,1.0,Yes,LLY,NO,Unable to contact both doctors in charge - bot...,Thursday,2021-08-26 09:59:00,50.0,No
2091,2021-08-27,4B,4616.0,3021029415,2021-08-27 08:04:00,NaT,2021-08-27 08:37:00,2021-08-27 09:00:00,Please help fill in PML Data,YSM,00:33:00,00:56:00,6.0,Yes,LLY,YES,NaN,Friday,2021-08-27 09:00:00,56.0,No
2175,2021-09-05,4A,4817.0,3021030961,2021-09-05 10:45:00,NaT,2021-09-05 11:31:00,NaT,,LLY,00:46:00,NaT,NaN,No,NaN,NaN,NaN,Sunday,2021-09-05 11:31:00,46.0,No
2180,2021-09-05,3A,3815.0,3021031288,2021-09-05 10:37:00,NaT,2021-09-05 11:33:00,NaT,,LLY,00:56:00,NaT,NaN,No,NaN,NaN,NaN,Sunday,2021-09-05 11:33:00,56.0,No
2269,2021-09-13,4B,4607.0,3021032074,2021-09-13 09:28:00,NaT,2021-09-13 09:45:00,2021-09-13 10:15:00,Please help fill in PML Data,TCE,00:17:00,00:47:00,7.0,Yes,TCE,NO,NaN,Monday,2021-09-13 10:15:00,47.0,No
2331,2021-09-17,3A,3819.0,3021033135,2021-09-17 18:45:00,NaT,2021-09-17 19:35:00,NaT,,TFP,00:50:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-09-17 19:35:00,50.0,No
2369,2021-09-20,3A,3822.0,3021031932,2021-09-20 09:30:00,NaT,2021-09-20 11:20:00,NaT,ALENDRONATE,TFP,01:50:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-09-20 11:20:00,50.0,No
2743,2021-10-30,3B,3618,3021038997,2021-10-30 12:50:00,NaT,2021-10-30 13:47:00,NaT,,LLY,00:57:00,NaT,NaN,No,NaN,NaN,NaN,Saturday,2021-10-30 13:47:00,57.0,No
2778,2021-11-03,3B,3618.0,3021039550,2021-11-03 08:00:00,NaT,2021-11-03 08:05:00,2021-11-03 08:50:00,,TFP,00:05:00,00:50:00,2.0,Yes,TFP,NaN,NaN,Wednesday,2021-11-03 08:50:00,50.0,No
2795,2021-11-05,3B,3605.0,3021039911,2021-11-05 08:00:00,2021-11-05 09:40:00,2021-11-05 10:12:00,2021-11-05 10:32:00,,DH,00:32:00,00:52:00,3.0,Yes,TFP,NaN,NaN,Friday,2021-11-05 10:32:00,52.0,No
2851,2021-11-11,3B,3612.0,3021040740,2021-11-11 09:57:00,NaT,2021-11-11 10:37:00,2021-11-11 10:45:00,,TCE,00:40:00,00:48:00,1.0,Yes,TCE,NaN,NaN,Thursday,2021-11-11 10:45:00,48.0,No
3014,2021-12-01,3B,3605.0,3021043241.0,2021-12-01 12:02:00,NaT,2021-12-01 13:01:00,NaT,NaN,LLY,00:59:00,NaT,NaN,No,NaN,NaN,NaN,Wednesday,2021-12-01 13:01:00,59.0,No
3015,2021-12-01,3B,3606.0,3021043487.0,2021-12-01 12:07:00,NaT,2021-12-01 13:03:00,NaT,NaN,LLY,00:56:00,NaT,NaN,No,NaN,NaN,NaN,Wednesday,2021-12-01 13:03:00,56.0,No
3150,2021-12-17,3B,3609.0,3021045341.0,2021-12-17 09:01:00,NaT,2021-12-17 09:25:00,2021-12-17 09:53:00,,TCE,00:24:00,00:52:00,10.0,Yes,TCE,NaN,NaN,Friday,2021-12-17 09:53:00,52.0,No
3197,2021-12-22,3B,3603.0,3021043609.0,2021-12-22 09:30:00,NaT,2021-12-22 09:50:00,2021-12-22 10:24:00,,LLY,00:20:00,00:54:00,1.0,Yes,TFP,NaN,NaN,Wednesday,2021-12-22 10:24:00,54.0,No

## Step 14: Create Office Hours column to check if case handled during offcie hours

Standard Office Hours: 8:30AM to 5:00PM

Taking into assumption that as long as Time TTO Dispensed is before 5:00PM

In [43]:
dfinal['Office Hours'] = np.where(dfinal['DateTime TTO Received'].isnull() | dfinal['DateTime TTO Dispensed'].isnull() , 'NA',
                            np.where(  #(dfinal['Time TTO Received'] >= pd.to_datetime('08:30:00').time()) & 
                                        (dfinal['DateTime TTO Dispensed'].dt.time <= pd.to_datetime('17:00:00').time()),
                                        'Yes', 'No'))

dfinal

<ipython-input-43-f2eca5f5c48c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Office Hours'] = np.where(dfinal['DateTime TTO Received'].isnull() | dfinal['DateTime TTO Dispensed'].isnull() , 'NA',

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed,TAT,Meet KPI,Office Hours
0,2021-01-04,4A,4811.0,3021000132.0,2021-01-04 09:52:00,NaT,2021-01-04 10:00:00,2021-01-04 10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 10:10:00,18.0,Yes,Yes
1,2021-01-04,3A,3828.0,3020041950.0,2021-01-04 08:34:00,NaT,2021-01-04 08:44:00,NaT,NaN,TFP,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:44:00,10.0,Yes,Yes
2,2021-01-04,3B,3606.0,3021000166.0,2021-01-04 09:15:00,2021-01-04 09:40:00,2021-01-04 09:50:00,2021-01-04 09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 09:55:00,15.0,Yes,Yes
3,2021-01-04,DAY,2011.0,3021000242.0,2021-01-04 10:09:00,NaT,2021-01-04 10:20:00,NaT,NaN,TFP,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 10:20:00,11.0,Yes,Yes
4,2021-01-04,4B,4610.0,3020044361.0,2021-01-04 08:37:00,NaT,2021-01-04 08:47:00,NaT,PATIENT FOR HOME ON WED,YSM,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:47:00,10.0,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3273,2021-12-31,3B,3611.0,3021047321.0,2021-12-31 09:50:00,NaT,2021-12-31 10:08:00,2021-12-31 10:26:00,NaN,TCE,00:18:00,00:36:00,6.0,Yes,TCE,NaN,NaN,Friday,2021-12-31 10:26:00,36.0,Yes,Yes
3274,2021-12-31,3B,3620.0,3021047584.0,2021-12-31 11:02:00,NaT,2021-12-31 11:05:00,2021-12-31 11:15:00,NaN,YZJ,00:03:00,00:13:00,1.0,Yes,TCE,NaN,NaN,Friday,2021-12-31 11:15:00,13.0,Yes,Yes
3275,2021-12-31,3A,3826.0,3021047432.0,2021-12-31 13:05:00,NaT,2021-12-31 13:16:00,NaT,NaN,YSM,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 13:16:00,11.0,Yes,Yes
3276,2021-12-31,3B,3610.0,3021046836.0,2021-12-31 15:10:00,NaT,2021-12-31 15:25:00,NaT,NaN,DH,00:15:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 15:25:00,15.0,Yes,Yes
3277,2021-12-31,3B,3605.0,3021047045.0,2021-12-31 16:26:00,NaT,2021-12-31 16:32:00,NaT,NaN,DH,00:06:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 16:32:00,6.0,Yes,Yes

In [44]:
dfinal[dfinal['Office Hours'] == 'No']

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed,TAT,Meet KPI,Office Hours
432,2021-02-19,4A,4816.0,3021005594.0,2021-02-19 16:45:00,NaT,2021-02-19 17:16:00,NaT,NaN,TFP,00:31:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-02-19 17:16:00,31.0,Yes,No
559,2021-03-04,4B,4613,3021004952.0,2021-03-04 16:55:00,NaT,2021-03-04 17:03:00,NaT,Please help fill in PML Data,TFP,00:08:00,NaT,NaN,No,NaN,Yes,NaN,Thursday,2021-03-04 17:03:00,8.0,Yes,No
923,2021-04-08,3B,3615,3021012103,2021-04-08 17:38:00,2021-04-08 17:39:00,2021-04-08 17:40:00,NaT,,TCE,00:01:00,NaT,NaN,No,NaN,NaN,NaN,Thursday,2021-04-08 17:40:00,1.0,Yes,No
1024,2021-04-16,4B,4618,3021013132,2021-04-16 17:23:00,NaT,2021-04-16 17:25:00,NaT,NaN,LLY,00:02:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-04-16 17:25:00,2.0,Yes,No
1025,2021-04-16,3B,3603,3021012527,2021-04-16 17:00:00,NaT,2021-04-16 17:24:00,NaT,NaN,LLY,00:24:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-04-16 17:24:00,24.0,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3181,2021-12-20,3B,3617.0,3021046261.0,2021-12-20 18:25:00,NaT,2021-12-20 18:30:00,NaT,,YZJ,00:05:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-12-20 18:30:00,5.0,Yes,No
3204,2021-12-22,3B,3610.0,3021046588.0,2021-12-22 18:13:00,NaT,2021-12-22 18:29:00,NaT,,YZJ,00:16:00,NaT,NaN,No,NaN,NaN,NaN,Wednesday,2021-12-22 18:29:00,16.0,Yes,No
3250,2021-12-28,3A,3828.0,3021047033.0,2021-12-28 18:20:00,NaT,2021-12-28 18:26:00,NaT,NaN,DH,00:06:00,NaT,NaN,No,NaN,NaN,NaN,Tuesday,2021-12-28 18:26:00,6.0,Yes,No
3251,2021-12-28,3A,3828.0,3021047033.0,2021-12-28 18:00:00,NaT,2021-12-28 18:04:00,NaT,NaN,DH,00:04:00,NaT,NaN,No,NaN,NaN,NaN,Tuesday,2021-12-28 18:04:00,4.0,Yes,No
3256,2021-12-29,3B,3615.0,3021047205.0,2021-12-29 17:45:00,NaT,2021-12-29 17:52:00,NaT,,LLY,00:07:00,NaT,NaN,No,NaN,NaN,NaN,Wednesday,2021-12-29 17:52:00,7.0,Yes,No

## Step 15: Calculate Average Time Taken from (Received to Checked) & (Checked to Dispensed)

In [45]:
#Get Duration Difference of Received to Checked
dfinal['Time Taken (Received to Checked)'] = (dfinal['DateTime TTO Checked'] - dfinal['DateTime TTO Received'])
#Get Duration Difference of Checked to Dispensed
dfinal['Time Taken (Checked to Dispensed)'] = (dfinal['DateTime TTO Dispensed'] - dfinal['DateTime TTO Checked'])

<ipython-input-45-bc274a3b0b31>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Time Taken (Received to Checked)'] = (dfinal['DateTime TTO Checked'] - dfinal['DateTime TTO Received'])
<ipython-input-45-bc274a3b0b31>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal['Time Taken (Checked to Dispensed)'] = (dfinal['DateTime TTO Dispensed'] - dfinal['DateTime TTO Checked'])

In [46]:
dfinal.head()

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed,TAT,Meet KPI,Office Hours,Time Taken (Received to Checked),Time Taken (Checked to Dispensed)
0,2021-01-04,4A,4811.0,3021000132.0,2021-01-04 09:52:00,NaT,2021-01-04 10:00:00,2021-01-04 10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 10:10:00,18.0,Yes,Yes,00:08:00,00:10:00
1,2021-01-04,3A,3828.0,3020041950.0,2021-01-04 08:34:00,NaT,2021-01-04 08:44:00,NaT,NaN,TFP,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:44:00,10.0,Yes,Yes,00:10:00,00:00:00
2,2021-01-04,3B,3606.0,3021000166.0,2021-01-04 09:15:00,2021-01-04 09:40:00,2021-01-04 09:50:00,2021-01-04 09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 09:55:00,15.0,Yes,Yes,00:35:00,00:05:00
3,2021-01-04,DAY,2011.0,3021000242.0,2021-01-04 10:09:00,NaT,2021-01-04 10:20:00,NaT,NaN,TFP,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 10:20:00,11.0,Yes,Yes,00:11:00,00:00:00
4,2021-01-04,4B,4610.0,3020044361.0,2021-01-04 08:37:00,NaT,2021-01-04 08:47:00,NaT,PATIENT FOR HOME ON WED,YSM,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:47:00,10.0,Yes,Yes,00:10:00,00:00:00

In [47]:
#Create new dataframe to get results of Average Time Taken for each (Received to Checked) & (Checked to Dispensed)
dfinal_avg_time = dfinal[['Date', 'Time Taken (Received to Checked)', 'Time Taken (Checked to Dispensed)']]
dfinal_avg_time.head()

,Date,Time Taken (Received to Checked),Time Taken (Checked to Dispensed)
0,2021-01-04,00:08:00,00:10:00
1,2021-01-04,00:10:00,00:00:00
2,2021-01-04,00:35:00,00:05:00
3,2021-01-04,00:11:00,00:00:00
4,2021-01-04,00:10:00,00:00:00

### Average time taken per day

In [48]:
#Re-instate time format
#dfinal_avg_time['Time Taken (Received to Checked)'] = pd.to_datetime(dfinal_avg_time['Time Taken (Received to Checked)'], infer_datetime_format=True).dt.time
#dfinal_avg_time['Time Taken (Checked to Dispensed)'] = pd.to_datetime(dfinal_avg_time['Time Taken (Checked to Dispensed)'], infer_datetime_format=True).dt.time

#Get average time taken per day
dfinal_avg_time = dfinal_avg_time.groupby(pd.to_datetime(dfinal_avg_time['Date']).dt.date).mean(numeric_only=False)
dfinal_avg_time

           Time Taken (Received to Checked) Time Taken (Checked to Dispensed)
Date
2021-01-04                         00:12:30                   00:01:52.500000
2021-01-05                         00:15:30                          00:17:30
2021-01-06                  00:14:21.818181                   00:07:05.454545
2021-01-07                  00:07:56.666666                          00:09:40
2021-01-08                         00:08:06                          00:02:36
...                                     ...                               ...
2021-12-27                         00:13:00                          00:00:00
2021-12-28                  00:07:16.363636                   00:00:54.545454
2021-12-29                  00:20:25.714285                   00:01:08.571428
2021-12-30                  00:30:26.666666                          00:01:40
2021-12-31                         00:09:18                          00:02:48

[288 rows x 2 columns]

In [49]:
#Remove miliseconds
dfinal_avg_time['Time Taken (Received to Checked)'] = dfinal_avg_time['Time Taken (Received to Checked)'].dt.floor('s')
dfinal_avg_time['Time Taken (Checked to Dispensed)'] = dfinal_avg_time['Time Taken (Checked to Dispensed)'].dt.floor('s')

dfinal_avg_time

           Time Taken (Received to Checked) Time Taken (Checked to Dispensed)
Date
2021-01-04                         00:12:30                          00:01:52
2021-01-05                         00:15:30                          00:17:30
2021-01-06                         00:14:21                          00:07:05
2021-01-07                         00:07:56                          00:09:40
2021-01-08                         00:08:06                          00:02:36
...                                     ...                               ...
2021-12-27                         00:13:00                          00:00:00
2021-12-28                         00:07:16                          00:00:54
2021-12-29                         00:20:25                          00:01:08
2021-12-30                         00:30:26                          00:01:40
2021-12-31                         00:09:18                          00:02:48

[288 rows x 2 columns]

In [50]:
#Rename Columns
dfinal_avg_time = dfinal_avg_time.rename({'Time Taken (Received to Checked)' : 'Avg Time Taken / Day (Received to Checked)', 'Time Taken (Checked to Dispensed)' : 'Avg Time Taken / Day (Checked to Dispensed)'}, axis=1)

In [51]:
#Merge the results from grouby for Avg Time Taken
dfinal = dfinal.merge(dfinal_avg_time, on='Date', how='left')
dfinal

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed,TAT,Meet KPI,Office Hours,Time Taken (Received to Checked),Time Taken (Checked to Dispensed),Avg Time Taken / Day (Received to Checked),Avg Time Taken / Day (Checked to Dispensed)
0,2021-01-04,4A,4811.0,3021000132.0,2021-01-04 09:52:00,NaT,2021-01-04 10:00:00,2021-01-04 10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 10:10:00,18.0,Yes,Yes,00:08:00,00:10:00,00:12:30,00:01:52
1,2021-01-04,3A,3828.0,3020041950.0,2021-01-04 08:34:00,NaT,2021-01-04 08:44:00,NaT,NaN,TFP,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:44:00,10.0,Yes,Yes,00:10:00,00:00:00,00:12:30,00:01:52
2,2021-01-04,3B,3606.0,3021000166.0,2021-01-04 09:15:00,2021-01-04 09:40:00,2021-01-04 09:50:00,2021-01-04 09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 09:55:00,15.0,Yes,Yes,00:35:00,00:05:00,00:12:30,00:01:52
3,2021-01-04,DAY,2011.0,3021000242.0,2021-01-04 10:09:00,NaT,2021-01-04 10:20:00,NaT,NaN,TFP,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 10:20:00,11.0,Yes,Yes,00:11:00,00:00:00,00:12:30,00:01:52
4,2021-01-04,4B,4610.0,3020044361.0,2021-01-04 08:37:00,NaT,2021-01-04 08:47:00,NaT,PATIENT FOR HOME ON WED,YSM,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:47:00,10.0,Yes,Yes,00:10:00,00:00:00,00:12:30,00:01:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3247,2021-12-31,3B,3611.0,3021047321.0,2021-12-31 09:50:00,NaT,2021-12-31 10:08:00,2021-12-31 10:26:00,NaN,TCE,00:18:00,00:36:00,6.0,Yes,TCE,NaN,NaN,Friday,2021-12-31 10:26:00,36.0,Yes,Yes,00:18:00,00:18:00,00:09:18,00:02:48
3248,2021-12-31,3B,3620.0,3021047584.0,2021-12-31 11:02:00,NaT,2021-12-31 11:05:00,2021-12-31 11:15:00,NaN,YZJ,00:03:00,00:13:00,1.0,Yes,TCE,NaN,NaN,Friday,2021-12-31 11:15:00,13.0,Yes,Yes,00:03:00,00:10:00,00:09:18,00:02:48
3249,2021-12-31,3A,3826.0,3021047432.0,2021-12-31 13:05:00,NaT,2021-12-31 13:16:00,NaT,NaN,YSM,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 13:16:00,11.0,Yes,Yes,00:11:00,00:00:00,00:09:18,00:02:48
3250,2021-12-31,3B,3610.0,3021046836.0,2021-12-31 15:10:00,NaT,2021-12-31 15:25:00,NaT,NaN,DH,00:15:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 15:25:00,15.0,Yes,Yes,00:15:00,00:00:00,00:09:18,00:02:48
3251,2021-12-31,3B,3605.0,3021047045.0,2021-12-31 16:26:00,NaT,2021-12-31 16:32:00,NaT,NaN,DH,00:06:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 16:32:00,6.0,Yes,Yes,00:06:00,00:00:00,00:09:18,00:02:48

In [52]:
#Replace 00:00:00 in time columns with np.NaN
dfinal['Time Taken (Received to Checked)'] = dfinal['Time Taken (Received to Checked)'].replace(pd.Timedelta(0), np.NaN)
dfinal['Time Taken (Checked to Dispensed)'] = dfinal['Time Taken (Checked to Dispensed)'].replace(pd.Timedelta(0), np.NaN)
dfinal['Avg Time Taken / Day (Received to Checked)'] = dfinal['Avg Time Taken / Day (Received to Checked)'].replace(pd.Timedelta(0), np.NaN)
dfinal['Avg Time Taken / Day (Checked to Dispensed)'] = dfinal['Avg Time Taken / Day (Checked to Dispensed)'].replace(pd.Timedelta(0), np.NaN)

In [53]:
dfinal

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed,TAT,Meet KPI,Office Hours,Time Taken (Received to Checked),Time Taken (Checked to Dispensed),Avg Time Taken / Day (Received to Checked),Avg Time Taken / Day (Checked to Dispensed)
0,2021-01-04,4A,4811.0,3021000132.0,2021-01-04 09:52:00,NaT,2021-01-04 10:00:00,2021-01-04 10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 10:10:00,18.0,Yes,Yes,00:08:00,00:10:00,00:12:30,00:01:52
1,2021-01-04,3A,3828.0,3020041950.0,2021-01-04 08:34:00,NaT,2021-01-04 08:44:00,NaT,NaN,TFP,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:44:00,10.0,Yes,Yes,00:10:00,NaT,00:12:30,00:01:52
2,2021-01-04,3B,3606.0,3021000166.0,2021-01-04 09:15:00,2021-01-04 09:40:00,2021-01-04 09:50:00,2021-01-04 09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 09:55:00,15.0,Yes,Yes,00:35:00,00:05:00,00:12:30,00:01:52
3,2021-01-04,DAY,2011.0,3021000242.0,2021-01-04 10:09:00,NaT,2021-01-04 10:20:00,NaT,NaN,TFP,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 10:20:00,11.0,Yes,Yes,00:11:00,NaT,00:12:30,00:01:52
4,2021-01-04,4B,4610.0,3020044361.0,2021-01-04 08:37:00,NaT,2021-01-04 08:47:00,NaT,PATIENT FOR HOME ON WED,YSM,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:47:00,10.0,Yes,Yes,00:10:00,NaT,00:12:30,00:01:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3247,2021-12-31,3B,3611.0,3021047321.0,2021-12-31 09:50:00,NaT,2021-12-31 10:08:00,2021-12-31 10:26:00,NaN,TCE,00:18:00,00:36:00,6.0,Yes,TCE,NaN,NaN,Friday,2021-12-31 10:26:00,36.0,Yes,Yes,00:18:00,00:18:00,00:09:18,00:02:48
3248,2021-12-31,3B,3620.0,3021047584.0,2021-12-31 11:02:00,NaT,2021-12-31 11:05:00,2021-12-31 11:15:00,NaN,YZJ,00:03:00,00:13:00,1.0,Yes,TCE,NaN,NaN,Friday,2021-12-31 11:15:00,13.0,Yes,Yes,00:03:00,00:10:00,00:09:18,00:02:48
3249,2021-12-31,3A,3826.0,3021047432.0,2021-12-31 13:05:00,NaT,2021-12-31 13:16:00,NaT,NaN,YSM,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 13:16:00,11.0,Yes,Yes,00:11:00,NaT,00:09:18,00:02:48
3250,2021-12-31,3B,3610.0,3021046836.0,2021-12-31 15:10:00,NaT,2021-12-31 15:25:00,NaT,NaN,DH,00:15:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 15:25:00,15.0,Yes,Yes,00:15:00,NaT,00:09:18,00:02:48
3251,2021-12-31,3B,3605.0,3021047045.0,2021-12-31 16:26:00,NaT,2021-12-31 16:32:00,NaT,NaN,DH,00:06:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 16:32:00,6.0,Yes,Yes,00:06:00,NaT,00:09:18,00:02:48

### Average time taken per month

In [54]:
dfinal['Month']= pd.to_datetime(dfinal['Date']).dt.month_name()

In [55]:
dfinal_avg_time = dfinal[['Date', 'Time Taken (Received to Checked)', 'Time Taken (Checked to Dispensed)']]

dfinal_avg_time['Month']= pd.to_datetime(dfinal_avg_time['Date']).dt.month_name()

#Get average time taken per month
dfinal_avg_time= dfinal_avg_time.groupby('Month').agg({'Time Taken (Received to Checked)': np.sum, 'Time Taken (Checked to Dispensed)': np.sum})

x = dfinal_avg_time['Time Taken (Received to Checked)'] / np.timedelta64(1, 'm')
y = dfinal.groupby('Month')['Time Taken (Received to Checked)'].count()

dfinal_avg_time['Avg Time Taken / Month (Received to Checked)'] = (x/y)

dfinal_avg_time['Avg Time Taken / Month (Received to Checked)'] = pd.to_datetime(dfinal_avg_time['Avg Time Taken / Month (Received to Checked)'], unit='m').apply(lambda x: x.strftime("%H:%M:%S"))

<ipython-input-55-7d6bd2f7bf42>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfinal_avg_time['Month']= pd.to_datetime(dfinal_avg_time['Date']).dt.month_name()

In [56]:
a = dfinal_avg_time['Time Taken (Checked to Dispensed)'] / np.timedelta64(1, 'm')
b = dfinal.groupby('Month')['Time Taken (Checked to Dispensed)'].count()

dfinal_avg_time['Avg Time Taken / Month (Checked to Dispensed)'] = (a/b)

dfinal_avg_time['Avg Time Taken / Month (Checked to Dispensed)'] = pd.to_datetime(dfinal_avg_time['Avg Time Taken / Month (Checked to Dispensed)'], unit='m').apply(lambda x: x.strftime("%H:%M:%S"))

In [57]:
dfinal_avg_time = dfinal_avg_time.drop(dfinal_avg_time.columns[[0, 1]], axis=1)

dfinal = dfinal.merge(dfinal_avg_time, on='Month', how='left')

dfinal['Avg Time Taken / Month (Received to Checked)'] = pd.to_timedelta(dfinal['Avg Time Taken / Month (Received to Checked)'])
dfinal['Avg Time Taken / Month (Checked to Dispensed)'] = pd.to_timedelta(dfinal['Avg Time Taken / Month (Checked to Dispensed)'])
dfinal

,Date,Ward,Room/Bed,Case Number,DateTime TTO Received,DateTime (Meds Sent Down),DateTime TTO Checked,DateTime (Counselled),Remarks,Checked By (Pharmacist),Time Taken (Ready for Collection),Time Taken (to Counselling),No. of Drugs,Bedside Counselling Candidate,Dispensed by,PML,No PML Remarks,Weekday,DateTime TTO Dispensed,TAT,Meet KPI,Office Hours,Time Taken (Received to Checked),Time Taken (Checked to Dispensed),Avg Time Taken / Day (Received to Checked),Avg Time Taken / Day (Checked to Dispensed),Month,Avg Time Taken / Month (Received to Checked),Avg Time Taken / Month (Checked to Dispensed)
0,2021-01-04,4A,4811.0,3021000132.0,2021-01-04 09:52:00,NaT,2021-01-04 10:00:00,2021-01-04 10:10:00,NaN,TFP,00:08:00,00:18:00,3.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 10:10:00,18.0,Yes,Yes,00:08:00,00:10:00,00:12:30,00:01:52,January,00:13:10,00:16:21
1,2021-01-04,3A,3828.0,3020041950.0,2021-01-04 08:34:00,NaT,2021-01-04 08:44:00,NaT,NaN,TFP,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:44:00,10.0,Yes,Yes,00:10:00,NaT,00:12:30,00:01:52,January,00:13:10,00:16:21
2,2021-01-04,3B,3606.0,3021000166.0,2021-01-04 09:15:00,2021-01-04 09:40:00,2021-01-04 09:50:00,2021-01-04 09:55:00,NaN,TFP,00:10:00,00:15:00,2.0,Yes,TFP,NaN,NaN,Monday,2021-01-04 09:55:00,15.0,Yes,Yes,00:35:00,00:05:00,00:12:30,00:01:52,January,00:13:10,00:16:21
3,2021-01-04,DAY,2011.0,3021000242.0,2021-01-04 10:09:00,NaT,2021-01-04 10:20:00,NaT,NaN,TFP,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 10:20:00,11.0,Yes,Yes,00:11:00,NaT,00:12:30,00:01:52,January,00:13:10,00:16:21
4,2021-01-04,4B,4610.0,3020044361.0,2021-01-04 08:37:00,NaT,2021-01-04 08:47:00,NaT,PATIENT FOR HOME ON WED,YSM,00:10:00,NaT,NaN,No,NaN,NaN,NaN,Monday,2021-01-04 08:47:00,10.0,Yes,Yes,00:10:00,NaT,00:12:30,00:01:52,January,00:13:10,00:16:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3247,2021-12-31,3B,3611.0,3021047321.0,2021-12-31 09:50:00,NaT,2021-12-31 10:08:00,2021-12-31 10:26:00,NaN,TCE,00:18:00,00:36:00,6.0,Yes,TCE,NaN,NaN,Friday,2021-12-31 10:26:00,36.0,Yes,Yes,00:18:00,00:18:00,00:09:18,00:02:48,December,00:22:44,00:13:46
3248,2021-12-31,3B,3620.0,3021047584.0,2021-12-31 11:02:00,NaT,2021-12-31 11:05:00,2021-12-31 11:15:00,NaN,YZJ,00:03:00,00:13:00,1.0,Yes,TCE,NaN,NaN,Friday,2021-12-31 11:15:00,13.0,Yes,Yes,00:03:00,00:10:00,00:09:18,00:02:48,December,00:22:44,00:13:46
3249,2021-12-31,3A,3826.0,3021047432.0,2021-12-31 13:05:00,NaT,2021-12-31 13:16:00,NaT,NaN,YSM,00:11:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 13:16:00,11.0,Yes,Yes,00:11:00,NaT,00:09:18,00:02:48,December,00:22:44,00:13:46
3250,2021-12-31,3B,3610.0,3021046836.0,2021-12-31 15:10:00,NaT,2021-12-31 15:25:00,NaT,NaN,DH,00:15:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 15:25:00,15.0,Yes,Yes,00:15:00,NaT,00:09:18,00:02:48,December,00:22:44,00:13:46
3251,2021-12-31,3B,3605.0,3021047045.0,2021-12-31 16:26:00,NaT,2021-12-31 16:32:00,NaT,NaN,DH,00:06:00,NaT,NaN,No,NaN,NaN,NaN,Friday,2021-12-31 16:32:00,6.0,Yes,Yes,00:06:00,NaT,00:09:18,00:02:48,December,00:22:44,00:13:46

## Step 16: Map Room/Bed No. to Ward No.¶

Match Room No. to its corresponding Ward.

In [58]:
#df_ward = pd.read_excel("../../Data/Pharmacy Dept/PEH TTO Data/PEH Wards.xlsx", sheet_name=0)

#df_ward

In [59]:
##df_ward.info()

In [60]:
#dfinal['Room/Bed'] = pd.to_numeric(dfinal['Room/Bed'], errors='coerce').convert_dtypes()
#dfinal['Room/Bed'] = dfinal['Room/Bed'].astype(object)

In [61]:
#dfinal = pd.merge(dfinal, df_ward, how='left', left_on=['Room/Bed'], right_on=['Room No.'])

#dfinal.head()

In [62]:
#dfinal[dfinal['Ward_y'].isnull()]

## Step 17: Export CLEANED to csv

In [63]:
#export to csv
dfinal.to_csv('../../Data/Pharmacy Dept/Data Cleaning/PEH_Data_Cleaned.csv', header=True, index=False)