# Pharmacy Department - Text Analysis

In this section, we will look at the 'Remarks' section to see if there are any significant results if we perform text analysis.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../../Data/Pharmacy Dept/Data Cleaning/Merged_Pharmacy_Dept_CLEANED.csv')

C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (2,3,5,6,7,8,9,10,11,12,13,14,15,16,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33197 entries, 0 to 33196
Data columns (total 42 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Date                                                          33196 non-null  object
 1   Ward                                                          30861 non-null  object
 2   Room                                                          3237 non-null   object
 3   Case Number                                                   33184 non-null  object
 4   Time TTO Received                                             33164 non-null  object
 5   Time (Meds Sent Down)                                         313 non-null    object
 6   Time TTO Checked                                              17592 non-null  object
 7   Time (Counselled)                                             993 non-null    object
 8   Remarks                                                       2986 non-null   object
 9   Checked By (Pharmacist)                                       3237 non-null   object
 10  Time Taken (Ready for Collection)                             3238 non-null   object
 11  Time Taken (to Counselling)                                   989 non-null    object
 12  No. of Drugs                                                  19296 non-null  object
 13  Bedside Counselling Candidate                                 3246 non-null   object
 14  Dispensed by                                                  990 non-null    object
 15  PML given?                                                    563 non-null    object
 16  If not given, WHY?! If given, were any interventions needed?  268 non-null    object
 17  Weekday                                                       33196 non-null  object
 18  Time TTO Dispensed                                            30287 non-null  object
 19  Overall Time Taken (mins)                                     32205 non-null  float64
 20  Meet KPI                                                      32105 non-null  object
 21  Office Hours                                                  32681 non-null  object
 22  Hospital                                                      33197 non-null  object
 23  Room Number                                                   2803 non-null   object
 24  TTO Type                                                      2794 non-null   object
 25  Checked by                                                    466 non-null    object
 26  Time to meet                                                  491 non-null    object
 27  Time TTO Reached                                              2399 non-null   object
 28  Time TTO Counselled                                           2055 non-null   object
 29  Counselled by                                                 420 non-null    object
 30  Limo Service                                                  1 non-null      object
 31  TTO Last Timestamp                                            2403 non-null   object
 32  Time (Dispensed)                                              5955 non-null   object
 33  Time (Dispensing)                                             6149 non-null   object
 34  Time (in Pharmacy)                                            2233 non-null   object
 35  Time (in Pigeon)                                              5430 non-null   object
 36  Time (Dispensed by Nurse)                                     960 non-null    object
 37  Time (Passed to Nurse)                                        281 non-null    object
 38  Comments (for delayed cases) (eg. Pt sleeping etc)            3854 non-null   object
 39  Time Taken To Pack (mins)                                     15475 non-null  object
 40  Time Taken to Reach Pt (mins)                                 15503 non-null  object
 41  Time TTO Packing                                              11623 non-null  object
dtypes: float64(1), object(41)
memory usage: 10.6+ MB

In [5]:
df

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),...,Time (Dispensed),Time (Dispensing),Time (in Pharmacy),Time (in Pigeon),Time (Dispensed by Nurse),Time (Passed to Nurse),Comments (for delayed cases) (eg. Pt sleeping etc),Time Taken To Pack (mins),Time Taken to Reach Pt (mins),Time TTO Packing
0,2021-03-15,4A,4825,302100869,13:50:00,NaN,13:53:00,NaN,,CHAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-11-05,4B,4606,302101606,08:35:00,NaN,08:49:00,09:00:00,Please help fill in PML Data,YSM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-08-26,3A,3841,302102993,12:32:00,NaN,12:39:00,NaN,,LLY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-03-10,3A,3838,302103523,11:37:00,NaN,11:43:00,NaN,,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-10-16,3B,3616,302103680,09:19:00,NaN,09:39:00,NaN,,LLY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33192,2021-12-31,824,NaN,4021107656,13:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,add on TTO,0:00,0:10,13:00:00
33193,2021-12-31,1205,NaN,4021107518,13:35:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PBH,0:12,NaN
33194,2021-12-31,1131,NaN,4021107644,14:08:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0:09,0:26,14:17:00
33195,2021-12-31,622,NaN,4021108689,13:59:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1431 pt in bathroom,0:10,0:42,14:09:00
33196,2021-12-31,609,NaN,4021108267,16:20:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0:05,0:25,16:25:00

# Analyze those with missing KPI or did not meet KPI

In [6]:
df_does_not_meet_kpi = df[(df["Meet KPI"].isnull()) | (df["Meet KPI"]=='No')]
df_does_not_meet_kpi

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),...,Time (Dispensed),Time (Dispensing),Time (in Pharmacy),Time (in Pigeon),Time (Dispensed by Nurse),Time (Passed to Nurse),Comments (for delayed cases) (eg. Pt sleeping etc),Time Taken To Pack (mins),Time Taken to Reach Pt (mins),Time TTO Packing
205,2021-01-26,3B,3609,3021002242,09:25:00,09:36:00,09:55:00,10:35:00,NaN,YSM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,2021-01-25,4B,4612,3021002435,08:53:00,NaN,08:55:00,10:50:00,NaN,DH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,2021-01-26,3B,3610,3021002640,09:00:00,09:36:00,10:00:00,10:35:00,NaN,YSM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435,2021-02-17,3A,3821,3021005452,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,2021-02-25,3B,3606,3021006433,09:13:00,09:30:00,09:58:00,10:16:00,NaN,CHAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33186,2021-12-31,625,NaN,4021105764,08:40:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1200 can go,0:05,3:49,08:45:00
33189,2021-12-31,615,NaN,4021108306,12:01:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0:14,0:32,12:15:00
33191,2021-12-31,817,NaN,4021107490,12:05:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0:16,0:38,12:21:00
33194,2021-12-31,1131,NaN,4021107644,14:08:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0:09,0:26,14:17:00
33195,2021-12-31,622,NaN,4021108689,13:59:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1431 pt in bathroom,0:10,0:42,14:09:00

In [7]:
df2 = df_does_not_meet_kpi[df_does_not_meet_kpi.Remarks.notnull()]

In [8]:
df2

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),...,Time (Dispensed),Time (Dispensing),Time (in Pharmacy),Time (in Pigeon),Time (Dispensed by Nurse),Time (Passed to Nurse),Comments (for delayed cases) (eg. Pt sleeping etc),Time Taken To Pack (mins),Time Taken to Reach Pt (mins),Time TTO Packing
544,2021-05-03,3B,3606,3021006885,09:30:00,09:42:00,10:25:00,10:30:00,,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
787,2021-03-25,4B,4605,3021010026,09:44:00,NaN,10:08:00,10:40:00,Please help fill in PML Data,YSM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1250,2021-10-05,DAY,2011,3021016241,11:31:00,NaN,12:23:00,NaN,,YSL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1324,2021-05-20,3A,3841,3021017176,20:35:00,NaN,21:26:00,NaN,Checked by duty manager,ANC SITI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1331,2021-05-19,4B,4619,3021017254,10:00:00,NaN,10:50:00,NaN,passed to SN,DH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5980,2021-12-07,NaN,NaN,1021088820.0,09:18:00,NaN,09:51:00,NaN,"[""9W remaining meds""]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5982,2021-12-07,NaN,NaN,1021087385.0,10:44:00,NaN,10:54:00,NaN,"[""Patient not available""]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5991,2021-12-06,NaN,NaN,1021088584.0,08:20:00,NaN,08:38:00,NaN,"[""Patient not available""]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6011,2021-12-04,NaN,NaN,1021085926.0,11:14:00,NaN,11:21:00,NaN,"[""Add-on medications""]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6044,2021-12-01,NaN,NaN,1021086185.0,09:39:00,NaN,10:30:00,NaN,"[""9W remaining meds""]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#df_does_not_meet_kpi['Remarks'] = df_does_not_meet_kpi['Remarks'].astype(str)
#df_does_not_meet_kpi['word_count'] = df_does_not_meet_kpi['Remarks'].apply(lambda x : len(x.split()))
#df_does_not_meet_kpi['char_count'] = df_does_not_meet_kpi['Remarks'].apply(lambda x : len(x.replace(" ","")))
#df_does_not_meet_kpi['word_density'] = df_does_not_meet_kpi['word_count'] / (df_does_not_meet_kpi['char_count'] + 1)
#df_does_not_meet_kpi['punc_count'] = df_does_not_meet_kpi['Remarks'].apply(lambda x : len([a for a in x if a in punc]))

#df_does_not_meet_kpi[['word_count', 'char_count', 'word_density']].head(10)

In [10]:
# lower casing
df2['Remarks_Lower']= df2['Remarks'].str.lower()

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
#removal of punctuation 
df2['Remarks_Lower'] = df2['Remarks_Lower'].str.replace(r'[^\w\s]+', '')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [12]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [13]:
#removal of stopwords
df2['Remarks_Lower']  = df2['Remarks_Lower'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
df2

,Date,Ward,Room,Case Number,Time TTO Received,Time (Meds Sent Down),Time TTO Checked,Time (Counselled),Remarks,Checked By (Pharmacist),...,Time (Dispensing),Time (in Pharmacy),Time (in Pigeon),Time (Dispensed by Nurse),Time (Passed to Nurse),Comments (for delayed cases) (eg. Pt sleeping etc),Time Taken To Pack (mins),Time Taken to Reach Pt (mins),Time TTO Packing,Remarks_Lower
544,2021-05-03,3B,3606,3021006885,09:30:00,09:42:00,10:25:00,10:30:00,,TFP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
787,2021-03-25,4B,4605,3021010026,09:44:00,NaN,10:08:00,10:40:00,Please help fill in PML Data,YSM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,please help fill pml data
1250,2021-10-05,DAY,2011,3021016241,11:31:00,NaN,12:23:00,NaN,,YSL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1324,2021-05-20,3A,3841,3021017176,20:35:00,NaN,21:26:00,NaN,Checked by duty manager,ANC SITI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,checked duty manager
1331,2021-05-19,4B,4619,3021017254,10:00:00,NaN,10:50:00,NaN,passed to SN,DH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,passed sn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5980,2021-12-07,NaN,NaN,1021088820.0,09:18:00,NaN,09:51:00,NaN,"[""9W remaining meds""]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9w remaining meds
5982,2021-12-07,NaN,NaN,1021087385.0,10:44:00,NaN,10:54:00,NaN,"[""Patient not available""]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,patient available
5991,2021-12-06,NaN,NaN,1021088584.0,08:20:00,NaN,08:38:00,NaN,"[""Patient not available""]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,patient available
6011,2021-12-04,NaN,NaN,1021085926.0,11:14:00,NaN,11:21:00,NaN,"[""Add-on medications""]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,addon medications
6044,2021-12-01,NaN,NaN,1021086185.0,09:39:00,NaN,10:30:00,NaN,"[""9W remaining meds""]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9w remaining meds

In [15]:
from collections import Counter
cnt = Counter()
for text in df2['Remarks_Lower'].values:
    for word in text.split():
        cnt[word] += 1
        
cnt.most_common(10)

[('sn', 97),
 ('passed', 87),
 ('remaining', 80),
 ('meds', 76),
 ('9w', 73),
 ('patient', 67),
 ('available', 51),
 ('addon', 36),
 ('medications', 34),
 ('tto', 29)]

In [ ]:
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
word_string=" ".join(df2['Remarks_Lower'].str.lower())
wordcloud = WordCloud(stopwords=STOPWORDS,
                          background_color='white', 
                      max_words=300
                         ).generate(word_string)

In [ ]:
plt.clf()
plt.imshow(wordcloud)
plt.axis('off')
plt.show()

In [ ]:
# for both pharm and cc
CC: no of calls - predict no of calls in the following years by months, days 
    --> to find out what is the predicted peak in terms of month, weekday
    
Pharm: no of TTO - PREDICT NO OF tto in the following years by month, days